/*
 * demolition man
 * back_in_the_fridge.c
 *
 *
 * written by James Cardona
 *
 * handles the lock freezes and the trigger of multiballs
 *
 *
 */
/* CALLSET_SECTION (back_in_the_fridge, __machine5__) */


#include <freewpc.h>
#include "dm/global_constants.h"
#include <diverter.h> //autogenerated by divhold.ct
#include <eb.h>
#include "shaker.h"
#include <system/device.h>
#include "search.h"
#include <coin.h>


//local variables
score_t 	back_in_the_fridge_score;
U8			back_in_the_fridge_shots_made;
U8			back_in_the_fridge_mode_timer;
U8 			back_in_the_fridge_display_counter;
U8 			BITF_TOGGLE;
__boolean is_back_in_the_fridge_running;
__boolean is_back_in_the_fridge_ending;
__boolean is_back_in_the_fridge_in_ball_save;


//internally called function prototypes  --external found at protos.h
void back_in_the_fridge_animation_display_effect (U16 start_frame, U16 end_frame);
void back_in_the_fridge_frame_bitfade_fast (U16 frame);
void back_in_the_fridge_shot_made(void);
void back_in_the_fridge_mode_expire (void);
void enable_back_in_the_fridge(void);
void back_in_the_fridge_player_reset (void);
void back_in_the_fridge_mode_init(void);
void back_in_the_fridge_start_balls(void);
void back_in_the_fridge_mode_exit (void);
void start_back_in_the_fridge(void);


/****************************************************************************
 * multiball definition structure
 ***************************************************************************/
struct timed_mode_ops back_in_the_fridge_mode = {
	DEFAULT_MODE,
	.init = back_in_the_fridge_mode_init,
	.exit = back_in_the_fridge_mode_expire,
	.gid = GID_PLD_MODE_RUNNING,
	.music = MUS_MB_B,
//	.deff_starting = DEFF_BITF_START_EFFECT, //STARTED BELOW
	.deff_running = DEFF_BITF_EFFECT,
//	.deff_ending = DEFF_BITF_END_EFFECT,
	.prio = PRI_MULTIBALL,
	.init_timer = 60, //we lose about 10 secs in the startup
	.timer = &back_in_the_fridge_mode_timer,
	.grace_timer = 2, //default is 2
//	.pause = system_timer_pause,
};





/****************************************************************************
 * reminder when mode enabled but not started yet
 ***************************************************************************/
__boolean get_back_in_the_fridge_running (void) {
	if(is_back_in_the_fridge_running) return TRUE;
	else return FALSE;
}


__boolean get_is_back_in_the_fridge_in_ball_save (void) {
	if(is_back_in_the_fridge_in_ball_save) return TRUE;
	else return FALSE;
}



__boolean get_back_in_the_fridge_ending (void) {
	if(is_back_in_the_fridge_ending) return TRUE;
	else return FALSE;
}


void kill_back_in_the_fridge (void) {
	is_back_in_the_fridge_running = FALSE;
	flag_off(FLAG_BACK_IN_THE_FRIDGE_ACTIVATED);
}



//this called by cryoprison multiball when it reaches single_ball_play or end ball
//to enable this wizard mode
void enable_back_in_the_fridge(void) {
	flag_on(FLAG_BACK_IN_THE_FRIDGE_ACTIVATED);
}//end of function






/****************************************************************************
 * initialize  and exit
 ***************************************************************************/
CALLSET_ENTRY (back_in_the_fridge, start_ball) {
	is_back_in_the_fridge_running = FALSE;
	is_back_in_the_fridge_ending = FALSE;
	is_back_in_the_fridge_in_ball_save = FALSE;
}//end of function



CALLSET_ENTRY (back_in_the_fridge, start_player) {
	flag_off(FLAG_BACK_IN_THE_FRIDGE_ACTIVATED);
	score_zero(back_in_the_fridge_score);
	back_in_the_fridge_shots_made = 0; //these need to be zeroed in before we enter the mode so bonus doesn't fake trigger
	task_kill_gid(GID_BACK_IN_THE_FRIDGE_REMINDER);
	//for testing
//	enable_back_in_the_fridge();
}//end of function



void back_in_the_fridge_ender_task (void) {
	while (back_in_the_fridge_mode_timer > 6 ) {
		task_sleep_sec(1);
	}//end of loop
	is_back_in_the_fridge_in_ball_save = FALSE;
	task_exit();
}//end of function





void back_in_the_fridge_mode_init(void) {
	flag_off(FLAG_BACK_IN_THE_FRIDGE_ACTIVATED);
	is_back_in_the_fridge_running = TRUE;
	is_back_in_the_fridge_in_ball_save = TRUE;
	task_kill_gid(GID_BACK_IN_THE_FRIDGE_REMINDER);
	computer_light_temp_off();
	deff_start_sync (DEFF_BITF_START_EFFECT);

	back_in_the_fridge_display_counter = 0;
	BITF_TOGGLE = 0;

//	kill_combos();
	diverter_stop();//defined in divhold2.ct

	score_add (back_in_the_fridge_score, score_table[BACK_IN_THE_FRIDGE_SCORE]);
	score (BACK_IN_THE_FRIDGE_SCORE);
	//	back_in_the_fridge_start_music = FALSE; //kill the start music

	//since mode ends by disabling flippers and allowing all balls to drain
	//we need to add a ball to the player
	increment_extra_balls_bitf ();

	is_back_in_the_fridge_ending = TRUE;  //this will cause the ending deff to play instead of the bonus deff on the last ball drain
	set_all_jackpots();
	set_ball_count (5);
//	task_sleep_sec(6); //takes about 6 secs to get all the balls on the playfield
	task_create_gid1 (GID_BACK_IN_THE_FRIDGE_ENDER, back_in_the_fridge_ender_task);

	//recount the trough every 5 secs - this is to handle situations
	//where too many drains in rapid succession cause the game to lose
	//count of live balls - this only happens during MB
	callset_invoke (mb_trough_recount_timer_start);
	set_dm_mode2(BITF_COMPLETED); //for BONUS
}//end of function






//this is an exit on timeout, balls still in play
void back_in_the_fridge_mode_expire (void) {
	flipper_disable();

	//there may still be trough kicks in the stack - clear them out

	leff_start(LEFF_TURN_OFF_GI);

	callset_invoke (trough_zero_out_kick_request);

	//just in case - make sure this is running
	ball_search_monitor_start ();

//	task_sleep_sec(5);
//	do {
//		task_sleep_sec(4);
//		callset_invoke (dev_trough_recount);
//	} while (!in_bonus);


}//end of function






//this is an exit on end of ball
//must do this differently to prevent excessive cycling of diverter which
//tends to blow fuses
//should never hit this if all goes as designed
void back_in_the_fridge_mode_exit (void) {
	//there may still be trough kicks in the stack - clear them out
	callset_invoke (trough_zero_out_kick_request);

	is_back_in_the_fridge_running = FALSE ;
	flag_off(FLAG_BACK_IN_THE_FRIDGE_ACTIVATED);
	timed_mode_end2(&back_in_the_fridge_mode);

	//just in case - make sure this is running
	ball_search_monitor_start ();

	callset_invoke (mb_trough_recount_timer_exit);
}//end of function





/****************************************************************************
 * external event listeners
 ****************************************************************************/
CALLSET_ENTRY (back_in_the_fridge, music_refresh)  { if (in_game && is_back_in_the_fridge_running)	music_request (MUS_MB_B, PRI_GAME_QUICK7); }
CALLSET_ENTRY (back_in_the_fridge, display_update) { if (is_back_in_the_fridge_running) 	deff_start_bg (DEFF_BITF_EFFECT, PRI_MULTIBALL); }
CALLSET_ENTRY (back_in_the_fridge, end_ball, tilt) { if (is_back_in_the_fridge_running)  	back_in_the_fridge_mode_exit(); }//end of function






/****************************************************************************
 *
 * body
 *
 ***************************************************************************/
void start_back_in_the_fridge(void) {
	timed_mode_begin (&back_in_the_fridge_mode);
}//end of function




void back_in_the_fridge_shot_made(void) {
	score_add (back_in_the_fridge_score, score_table[BACK_IN_THE_FRIDGE_HIT_SCORE]);
	score (BACK_IN_THE_FRIDGE_HIT_SCORE);
	back_in_the_fridge_shots_made++;

	if (system_config.disable_shaker == NO) {
		if (system_config.extra_shaker == YES) 	shaker_start (SHAKER_HALF_ON, 2);
		else									shaker_start (SHAKER_ONE_QUARTER_ON, 2);
	}//end of shaker call

	switch (back_in_the_fridge_shots_made % 5) {
		case 1:	leff_start (LEFF_JACKPOT1); break;
		case 2:	leff_start (LEFF_JACKPOT2); break;
		case 3:	leff_start (LEFF_JACKPOT3); break;
		case 4:	leff_start (LEFF_JACKPOT4); break;
		default: leff_start (LEFF_JACKPOT); break;
	}
	deff_start (DEFF_BITF_HIT_EFFECT);

	//this is a backup to the ender task to prevent infinite loops
	if	(back_in_the_fridge_mode_timer < 6 )	is_back_in_the_fridge_in_ball_save = FALSE;
}//end of function




/****************************************************************************
 *
 * DMD display and sound effects
 *
 ****************************************************************************/
void back_in_the_fridge_animation_display_effect (U16 start_frame, U16 end_frame){
	U16 fno;
	for (fno = start_frame; fno <= end_frame; fno += 2) {
		dmd_alloc_pair ();
		frame_draw(fno);
		dmd_show2 ();
		task_sleep (TIME_100MS);
	}//end of inner loop
}//end of function



void back_in_the_fridge_frame_bitfade_fast (U16 frame){
	dmd_sched_transition (&trans_bitfade_fast);
	dmd_alloc_pair ();
	frame_draw(frame);
	dmd_show2 ();
	task_sleep (TIME_100MS);
}




void bitf_info_effect_deff(void) {
	dmd_clean_page_high ();
	dmd_clean_page_low ();
	font_render_string_center (&font_term6, DMD_MIDDLE_X, DMD_MED_CY_1, "SHOOT LEFT LOOP");
	font_render_string_center (&font_var5, DMD_MIDDLE_X, DMD_SMALL_CY_3 - 3, "FOR");
		font_render_string_center (&font_halobold12, DMD_MIDDLE_X, DMD_BIG_CY_Bot, "FRIDGE");
	dmd_sched_transition (&trans_scroll_down);
	dmd_show_low();
	task_sleep_sec (2);
	deff_exit ();
}//end of mode_effect_deff




void bitf_start_effect_deff(void) {
	if (DM_IN_DMD_TEST) score_zero(back_in_the_fridge_score);
	sound_start (ST_ANY, STEAM, SL_1S, PRI_GAME_QUICK2);
	back_in_the_fridge_animation_display_effect (IMG_FREEZE_A_START, IMG_FREEZE_A_END);
	U8 i;
	for (i = 0; i < 3; i++) {
			sound_start (ST_EFFECT, SPECIAL_EFFECT, SL_500MS, PRI_GAME_QUICK2);
			dmd_alloc_pair ();
			dmd_clean_page_low ();
			font_render_string_center (&font_halobold12, DMD_MIDDLE_X, DMD_BIG_CY_Top, "BACK IN");
			dmd_copy_low_to_high ();
			dmd_show_low ();
			dmd_invert_page (dmd_low_buffer);
			deff_swap_low_high (5, TIME_100MS);
		sound_start (ST_EFFECT, SPECIAL_EFFECT, SL_1S, PRI_GAME_QUICK2);
		dmd_clean_page_low ();
		font_render_string_center (&font_halobold12, DMD_MIDDLE_X, DMD_BIG_CY_Bot, "FRIDGE");
		dmd_copy_low_to_high ();
		dmd_show_low ();
		dmd_invert_page (dmd_low_buffer);
		deff_swap_low_high (5, TIME_100MS);
	}

	sound_start (ST_SPEECH, SPCH_BACK_IN_FRIDGE, SL_4S, PRI_GAME_QUICK4);
	deff_swap_low_high (3, TIME_500MS);
	deff_exit ();
}//end of mode_effect_deff





U8	back_in_the_fridge_SoundCounter;
void back_in_the_fridge_jackpot_sounds_task(void) {
	if (DM_IN_DMD_TEST) {	if (++back_in_the_fridge_SoundCounter > 4) back_in_the_fridge_SoundCounter = 0; }
	else			back_in_the_fridge_SoundCounter = random_scaled(5);
	U8 i;
	for (i = 0; i < 5; i++) {
		sound_start (ST_EFFECT, MACHINE14_SHORT, SL_1S, PRI_GAME_QUICK4);
		task_sleep (TIME_100MS);
	}
	task_sleep (TIME_500MS);
	switch (back_in_the_fridge_SoundCounter) {
		case 0: 	sound_start (ST_SPEECH, SPCH_TRESPASSING, SL_2S, PRI_GAME_QUICK4); break;
		case 1: 	sound_start (ST_SPEECH, SPCH_LOVE_THIS_GUY, SL_2S, PRI_GAME_QUICK4); break;
		case 2: 	sound_start (ST_SPEECH, SPCH_PHOENIX_LONG, SL_2S, PRI_GAME_QUICK4); break;
		case 3: 	sound_start (ST_SPEECH, SPCH_JOHN_SCREAM, SL_2S, PRI_GAME_QUICK4); break;
		case 4: 	sound_start (ST_SPEECH, SPCH_UNDER_ARREST, SL_2S, PRI_GAME_QUICK4); break;
	}//end of switch
	task_exit();
}//end of mode_effect_deff





U8 	back_in_the_fridge_MessageCounter;
void bitf_hit_effect_deff(void) {
	if (DM_IN_DMD_TEST) {
				if (++back_in_the_fridge_MessageCounter > 1) back_in_the_fridge_MessageCounter = 0;
				U8 i;
				for (i = 0; i < 3; i++) {
					score_add (back_in_the_fridge_score, score_table[BACK_IN_THE_FRIDGE_HIT_SCORE]);
					back_in_the_fridge_shots_made++;
				}
	}
	else			back_in_the_fridge_MessageCounter = random_scaled(6);

	task_create_gid1 (GID_back_in_the_fridge_JACKPOT_SOUND, back_in_the_fridge_jackpot_sounds_task);

	if (!TROUGH_TEST) {
				dmd_clean_page_high ();//
				dmd_clean_page_low ();//
				dmd_map_overlay ();
				dmd_clean_page_low ();
					font_render_string_center (&font_halobold12, DMD_MIDDLE_X, DMD_BIG_CY_Top, "BACK IN");
					font_render_string_center (&font_halobold12, DMD_MIDDLE_X, DMD_BIG_CY_Bot, "FRIDGE");
					dmd_text_outline ();
					dmd_alloc_pair ();
					switch (back_in_the_fridge_MessageCounter) {
						default:
						case 0: frame_draw (IMG_FREEZE_A_END); break;
						case 1: frame_draw (IMG_FREEZE_A_END - 4); break;
						case 2: frame_draw (IMG_FREEZE_A_END - 6); break;
						case 3: frame_draw (IMG_FREEZE_A_END - 8); break;
						case 4: frame_draw (IMG_FREEZE_A_END - 10); break;
						case 5: frame_draw (IMG_FREEZE_A_END - 12); break;
					}
					dmd_overlay_outline ();
					dmd_show2 ();
					task_sleep (TIME_500MS);
	}//end of not trough test
	deff_exit ();
}//end of mode_effect_deff





//done this way because we call it at the end of a ball
//so this is called from game.c logic, not normal logic
CALLSET_ENTRY (back_in_the_fridge, bitf_end) {
	deff_start_sync (DEFF_BITF_END_EFFECT);
}




void bitf_end_effect_deff (void) {
	task_sleep (TIME_100MS);	/* Wait a bit so the previous music_stop doesn't kill the sounds */

	dmd_alloc_low_clean ();
	sound_start (ST_ANY, SPECIAL_EFFECT, SL_1S, PRI_GAME_QUICK2);
		font_render_string_center (&font_halobold12, DMD_MIDDLE_X, DMD_BIG_CY_Top, "BACK IN");
		font_render_string_center (&font_halobold12, DMD_MIDDLE_X, DMD_BIG_CY_Bot, "FRIDGE");
	dmd_sched_transition (&trans_scroll_down);
	dmd_show_low ();
	task_sleep_sec (2);


	dmd_alloc_low_clean ();
	sound_start (ST_ANY, SPECIAL_EFFECT, SL_1S, PRI_GAME_QUICK2);
	sprintf ("%d MADE", back_in_the_fridge_shots_made);
		font_render_string_center (&font_halobold12, DMD_MIDDLE_X, DMD_MIDDLE_Y, sprintf_buffer);
	dmd_sched_transition (&trans_scroll_down);
	dmd_show_low ();
	task_sleep_sec (2);


	dmd_alloc_low_clean ();
	sound_start (ST_ANY, SPECIAL_EFFECT, SL_1S, PRI_GAME_QUICK2);
	sprintf_score (back_in_the_fridge_score);
	font_render_string_center (&font_fixed6, DMD_MIDDLE_X, DMD_MIDDLE_Y, sprintf_buffer);
	dmd_sched_transition (&trans_scroll_down);
	dmd_show_low ();
	task_sleep_sec (2);
	sound_start (ST_SPEECH, SPCH_BE_WELL_PHOENIX, SL_4S, PRI_GAME_QUICK4);
	is_back_in_the_fridge_ending = FALSE;

	//"in_test" means we are currently in the test menu (even if game is running in background)
	if (!in_test) callset_invoke (bonus_complete); //this tells game.c logic to continue with end ball stuff
	deff_exit ();
}//end of function





void bitf_effect_deff (void) {
	dmd_alloc_pair_clean();
	for (;;) {
		dmd_clean_page_low ();
//right side status display
		ll_score_draw_ball ();

//left side display
		sprintf_score(current_score);
		font_render_string_center (&font_var5, 50, 13, sprintf_buffer);
		font_render_string_right (&font_halobold12, 88, 1, "FRIDGE");

		sprintf ("%d", back_in_the_fridge_mode_timer);
		font_render_string_left (&font_halobold12, 1, 12, sprintf_buffer);

		if (	BITF_TOGGLE == 0) 	sprintf ("15 MILLION");
		else if (BITF_TOGGLE == 1)	sprintf ("SHOOT ARROWS");
		else if (BITF_TOGGLE == 2)	sprintf ("%d MADE", back_in_the_fridge_shots_made);
		font_render_string_center (&font_var5, 50, 27, sprintf_buffer);
		if (++back_in_the_fridge_display_counter % 5 == 0) { if (++BITF_TOGGLE > 2) BITF_TOGGLE = 0; }//change FORT_TOGGLE once per second
		dmd_show_low ();
		task_sleep (TIME_1S);
	}//END OF ENDLESS LOOP
}//end of function

