/*
 * demolition man
 * capture_simon.c
 *
 * written by James Cardona
 *
 * Location Description:
 * mode started by claw switch capture_simon
 *
 * Scoring Description: (original game)
 * The ball is dropped down a tunnel and served to the
 * right ramp just like the Underground. The seven
 * major shots are lit for 5 mil each for three shots.
 * A 25 million award for completing all three shots for a total of 40 million

 * Scoring Description: (my rules)
 * same as above except:
 * major shots are lit for 15 mil each for three shots.
 * A 50 million award for completing all three shots for a total of 95 million.
 *
 * estimate of average capture simon mode score: 30 million to 95 million
 *
 */
/* CALLSET_SECTION (capture_simon, __machine3__) */

#include <freewpc.h>
#include "dm/global_constants.h"
#include "clawmagnet.h"
#include <diverter.h> //autogenerated by divhold.ct
#include "capture_simon.h"
#include "ballsave.h"
#include <coin.h>


//constants
#define			CAP_SIM_EASY_GOAL 	 3
#define			CAP_SIM_MED_GOAL 	 4
#define			CAP_SIM_HARD_GOAL 	 5
#define 		CAP_SIM_GOAL_INCREMENT  1
#define 		CAP_SIM_GOAL_MAX 	 10


//local variables
U8			capture_simon_SoundCounter;
U8 			capture_simon_mode_shots_made;
U8 			capture_simon_mode_shots_goal;
U8			capture_simon_mode_timer;
score_t 	capture_simon_mode_score;
score_t 	capture_simon_mode_last_score;
score_t 	capture_simon_mode_next_score;
score_t 	capture_simon_mode_score_total_score;
U8 			capture_simon_arrow;
__boolean 	is_cap_sim_initial_start;
bool		capture_simon_suspend;

//external variables


//internally called function prototypes  --external found at protos.h
void capture_simon_reset (void);
void capture_simon_player_reset (void);
void capture_simon_effect_deff(void);
void capture_simon_mode_init (void);
void capture_simon_mode_expire (void);
void capture_simon_mode_exit (void);
void cap_simon_choose_random_flag_set(void);

/****************************************************************************
 * mode definition structure
 ***************************************************************************/
struct timed_mode_ops capture_simon_mode = {
	DEFAULT_MODE,
	.init = capture_simon_mode_init,
	.exit = capture_simon_mode_expire,
	.gid = GID_CAPTURE_SIMON_MODE_RUNNING,
	.music = MUS_MD_CAPTURE_SIMON,
	.deff_starting = DEFF_CAPTURE_SIMON_START_EFFECT,
	.deff_running = DEFF_CAPTURE_SIMON_EFFECT,
	.deff_ending = DEFF_CAPTURE_SIMON_END_EFFECT,
	.prio = PRI_GAME_MODE4,
	.init_timer = 48,
	.timer = &capture_simon_mode_timer,
	.grace_timer = 2,
	.pause = suspend_capture_simon,
};



/****************************************************************************
 * initialize  and exit
 ***************************************************************************/
void capture_simon_reset (void) {
	set_capture_simon_arrows_all_off ();
	is_cap_sim_initial_start = FALSE;

	if (get_dm_mode(CAP_SIM_COMPLETED) ) 	lamp_tristate_on (LM_CLAW_CAPTURE_SIMON);
	else 									lamp_tristate_off (LM_CLAW_CAPTURE_SIMON);
}//end of function


void capture_simon_player_reset (void) {
	capture_simon_mode_shots_made = 0;
	capture_simon_mode_shots_goal = CAP_SIM_EASY_GOAL;
	score_zero(capture_simon_mode_score_total_score);
	capture_simon_SoundCounter = 0;
	capture_simon_arrow = 0x0;
	capture_simon_suspend = FALSE;
}//end of function



//purpose here is to prevent underground from triggering since
//this shot feeds to underground
void capture_simon_startup_task (void) {
	is_cap_sim_initial_start = TRUE;
	task_sleep_sec(10);
	//this is just here in case deff hangs or does not play
	is_cap_sim_initial_start = FALSE;
	task_exit();
}//end of function




void capture_simon_mode_init (void) {
	capture_simon_suspend = FALSE;
	task_create_gid1(GID_CAP_SIM_START, capture_simon_startup_task);
	//the claw mode can expire on its own and since it is a lower priority it will not display
			//callset_invoke (end_claw_mode); // as this seemed to cause occasional crashes
			clawmagnet_off ();
			global_flag_off(GLOBAL_FLAG_IS_BALL_ON_CLAW);
			flipper_enable ();
			ballsave_add_time (system_config.mode_ballsave);
	capture_simon_mode_shots_made = 0;
	kill_combos ();
	//flash lamp for a time
	lamp_tristate_flash(LM_CLAW_CAPTURE_SIMON);
	task_sleep(TIME_500MS);
	lamp_tristate_on(LM_CLAW_CAPTURE_SIMON);
	//reset counter if first time run, otherwise do not - player may restart mode while currently running
	if (get_dm_mode(CAP_SIM_COMPLETED) ) 	{
		score_add(capture_simon_mode_next_score, score_table[CAPSIM_HIT_SCORE_2]);
	}
	else 									{
		score_zero(capture_simon_mode_score);
		score_zero(capture_simon_mode_last_score);
		score_zero(capture_simon_mode_next_score);
		score_add(capture_simon_mode_next_score, score_table[CAPSIM_HIT_SCORE_1]);
	}
	//this pause is here to give sounds time to finish
	task_sleep(TIME_500MS);
	task_sleep(TIME_500MS);
	task_sleep(TIME_500MS);
	cap_simon_choose_random_flag_set();
	all_arrow_update();
	demotime_increment();
}//end of function




//this is an exit on timeout, ball still in play
void capture_simon_mode_expire (void) {
	set_capture_simon_arrows_all_off ();
	all_arrow_update();
	is_cap_sim_initial_start = FALSE;

	capture_simon_mode_shots_goal += CAP_SIM_GOAL_INCREMENT;//increment goal for next time
	set_dm_mode(CAP_SIM_COMPLETED); //for next time

	combo_init ();
}//end of function



//this is an exit on end of ball
//must do this differently to prevent excessive cycling of diverter which
//tends to blow fuses
void capture_simon_mode_exit (void) {
		set_capture_simon_arrows_all_off ();
		all_arrow_update();
		is_cap_sim_initial_start = FALSE;

		capture_simon_mode_shots_goal += CAP_SIM_GOAL_INCREMENT;//increment goal for next time
		set_dm_mode(CAP_SIM_COMPLETED); //for next time

		timed_mode_end2 (&capture_simon_mode);
	}//end of function



/****************************************************************************
 * external event listeners
 ****************************************************************************/
CALLSET_ENTRY (capture_simon, music_refresh)  	{ if (in_game) timed_mode_music_refresh (&capture_simon_mode); }
CALLSET_ENTRY (capture_simon, display_update) 	{ if (in_game && !flag_test(FLAG_VIDEO_MODE_RUNNING) ) timed_mode_display_update (&capture_simon_mode); }

CALLSET_ENTRY (capture_simon, start_player) 	{ capture_simon_player_reset(); }
CALLSET_ENTRY (capture_simon, start_ball) 		{ capture_simon_reset(); }




CALLSET_ENTRY (capture_simon, end_ball, tilt) 		{
	if (timed_mode_running_p (&capture_simon_mode) ) capture_simon_mode_exit();
	set_capture_simon_arrows_all_off ();
	is_cap_sim_initial_start = FALSE;
}//end of function


/****************************************************************************
 *
 * body
 *
 ***************************************************************************/
bool get_is_capture_simon_initial_start (void) {
	return is_cap_sim_initial_start;
}//end of function


void set_capture_simon_arrows (U8 arrow_flag) {
	capture_simon_arrow |= arrow_flag;  // flag or unflag the bit
}//end of function



void set_capture_simon_arrows_all_off (void) {
	capture_simon_arrow = 0x0;
}//end of function



__boolean get_capture_simon_arrows (U8 arrow_flag) {
		if (capture_simon_arrow & arrow_flag) return TRUE;
		else return FALSE;
}//end of function



U8 get_capture_simon_timer (void) {
	if (timed_mode_running_p (&capture_simon_mode) ) 	return timed_mode_get_timer (&capture_simon_mode);
	else 												return (0);
}//end of function



U8 get_capture_simon_timer_total_time (void) {
	return timed_mode_get_timer_total (&capture_simon_mode);
}//end of function



bool is_capture_simon_running (void) {
	return timed_mode_running_p (&capture_simon_mode);
}//end of function


//this is used for when a video mode is started while mode is running
bool suspend_capture_simon (void) {
	if (capture_simon_suspend) return TRUE;
	else return FALSE;
}//end of function


void pause_capture_simon (bool state) {
	if (state) capture_simon_suspend = TRUE;
	else {
		//unpause and add a few seconds for lost delay time
		capture_simon_suspend = FALSE;
		timed_mode_add (&capture_simon_mode, 3);
	}
}//end of function

void add_time_to_capture_simon_mode (U8 time){
	timed_mode_add (&capture_simon_mode, time);
}//end of function




CALLSET_ENTRY (capture_simon, sw_claw_capture_simon) {
	if (in_game && !in_tilt) {
		timed_mode_begin (&capture_simon_mode);//start mode
	}
}//end of function



 //center ramp shot made during capture_simon mode
void capture_simon_made(void) {
	++capture_simon_mode_shots_made;
	score_zero(capture_simon_mode_last_score);
	if (get_dm_mode(CAP_SIM_COMPLETED) ) 	{
		score (CAPSIM_HIT_SCORE_2);
		score_add(capture_simon_mode_last_score, score_table[CAPSIM_HIT_SCORE_2]);
	}
	else {
		score (CAPSIM_HIT_SCORE_1);
		score_add(capture_simon_mode_last_score, score_table[CAPSIM_HIT_SCORE_1]);
	}
	score_add (capture_simon_mode_score, capture_simon_mode_last_score);
	score_add (capture_simon_mode_score_total_score, capture_simon_mode_last_score);

	if (capture_simon_mode_shots_made < capture_simon_mode_shots_goal ) {
			cap_simon_choose_random_flag_set();
			all_arrow_update();
			deff_start (DEFF_CAPTURE_SIMON_HIT_EFFECT);

	}	//IF FINAL CAPTURE SIMON SHOT MADE
	else {
		score (CAP_SIM_COMPLETED_SCORE);
		score_add(capture_simon_mode_score, score_table[CAP_SIM_COMPLETED_SCORE]);
		score_add (capture_simon_mode_score_total_score, score_table[CAP_SIM_COMPLETED_SCORE]);
		deff_start (DEFF_CAPTURE_SIMON_END_EFFECT);
		capture_simon_mode_exit();
		}
}//end of function



/****************************************************************************
 *
 * DMD display and sound effects
 *
 ****************************************************************************/
void cap_sim_animation_display_effect (U16 start_frame, U16 end_frame){
	U16 fno;
	for (fno = start_frame; fno <= end_frame; fno += 2) {
		dmd_alloc_pair ();
		frame_draw(fno);
		dmd_show2 ();
		task_sleep (TIME_100MS);
	}//end of inner loop
}



void capture_simon_frame_bitfade_fast (U16 frame){
	dmd_sched_transition (&trans_bitfade_fast);
	dmd_alloc_pair ();
	frame_draw(frame);
	dmd_show2 ();
	task_sleep (TIME_100MS);
}




void capture_simon_start_effect_deff(void) {
	dmd_alloc_pair_clean();
	sound_start (ST_SPEECH, SPCH_UNDER_ARREST, SL_3S, PRI_GAME_QUICK1);
	cap_sim_animation_display_effect (IMG_CAPSIMON_A_START, IMG_CAPSIMON_A_END);
	capture_simon_frame_bitfade_fast(IMG_SIMON_C_START);
	sound_start (ST_SPEECH, SPCH_SO_SCARED, SL_4S, PRI_GAME_QUICK1);
	cap_sim_animation_display_effect (IMG_SIMON_C_START, IMG_SIMON_C_END);
	dmd_map_overlay ();
	dmd_clean_page_low ();
		font_render_string_center (&font_halobold12, DMD_MIDDLE_X - 12, DMD_BIG_CY_Top, "CAPTURE");
		font_render_string_center (&font_halobold12, DMD_MIDDLE_X + 20, DMD_BIG_CY_Bot, "SIMON");
	dmd_text_outline ();
	dmd_alloc_pair ();
	frame_draw(IMG_SIMON_C_END);
	dmd_overlay_outline ();
	dmd_show2 ();
	task_sleep_sec (1);
	is_cap_sim_initial_start = FALSE;
	task_sleep_sec (1);
	deff_exit ();
}//end of mode_effect_deff





void capture_simon_hit_effect_deff(void) {
	U8 cap_simon_effect_randomizer;
	if (DM_IN_DMD_TEST) capture_simon_mode_shots_made++; //for testing only
	cap_simon_effect_randomizer = random_scaled(2);
	switch (cap_simon_effect_randomizer) {
		case 0 : sound_start (ST_SPEECH, SPCH_WES_LAUGH1, SL_4S, PRI_GAME_QUICK2); break;
		case 1 : sound_start (ST_SPEECH, SPCH_WES_LAUGH2, SL_4S, PRI_GAME_QUICK2); break;
	}

	dmd_alloc_pair_clean();
	//right side status display
	ll_score_draw_ball ();

	//left side display
	//	DRAW HAND CUFFS
		bitmap_blit (cuffs_3_bits, 0, 16);
		if (capture_simon_mode_shots_made == 0) font_render_string_right (&font_halobold12, 98, 1, "3 MORE");
		else if (capture_simon_mode_shots_made == 1) font_render_string_right (&font_halobold12, 98, 1, "2 MORE");
		else if (capture_simon_mode_shots_made == 2) font_render_string_right (&font_halobold12, 98, 1, "1 MORE");
		sprintf_score (capture_simon_mode_last_score);
		font_render_string_right (&font_term6, 98, 21, sprintf_buffer);
		dmd_show_low ();
		task_sleep_sec (2);

			font_render_string_right (&font_term6, 98, 21, sprintf_buffer);


	switch (cap_simon_effect_randomizer) {
	case 0 :
			//	DRAW FOOT STEPS RUNNING AWAY
				dmd_clean_page_low ();
				bitmap_blit (footstep_left_2_bits, 104, 18);
				dmd_show_low ();
				sound_start (ST_EFFECT, TOINK1, SL_1S, PRI_GAME_QUICK2);
				task_sleep (TIME_200MS);
						bitmap_blit (footstep_left_1_bits, 76, 6);
						sound_start (ST_EFFECT, TOINK2, SL_1S, PRI_GAME_QUICK2);
						dmd_show_low ();
						task_sleep (TIME_200MS);
					bitmap_blit (footstep_left_2_bits, 48, 18);
					dmd_show_low ();
					sound_start (ST_EFFECT, TOINK1, SL_1S, PRI_GAME_QUICK2);
					task_sleep (TIME_200MS);
				bitmap_blit (footstep_left_1_bits, 20, 6);
				sound_start (ST_EFFECT, TOINK2, SL_1S, PRI_GAME_QUICK2);
				task_sleep (TIME_200MS);
				dmd_show_low ();
				task_sleep_sec (1);
		break;
	case 1 :
				//	DRAW FOOT STEPS RUNNING AWAY
					dmd_clean_page_low ();
					bitmap_blit (footstep_right_2_bits, 0, 18);
					dmd_show_low ();
					sound_start (ST_EFFECT, TOINK1, SL_1S, PRI_GAME_QUICK2);
					task_sleep (TIME_200MS);
				bitmap_blit (footstep_right_1_bits, 28, 6);
				sound_start (ST_EFFECT, TOINK2, SL_1S, PRI_GAME_QUICK2);
				dmd_show_low ();
				task_sleep (TIME_200MS);
							bitmap_blit (footstep_right_2_bits, 56, 18);
							dmd_show_low ();
							sound_start (ST_EFFECT, TOINK1, SL_1S, PRI_GAME_QUICK2);
							task_sleep (TIME_200MS);
					bitmap_blit (footstep_right_1_bits, 84, 6);
					sound_start (ST_EFFECT, TOINK2, SL_1S, PRI_GAME_QUICK2);
					dmd_show_low ();
					task_sleep_sec (1);
			break;
	}//end of switch
	deff_exit ();
}//end of mode_effect_deff







void capture_simon_end_effect_deff(void) {
	//capture_simon_mode_shots_made++; //for testing only
	dmd_alloc_low_clean ();
	sound_start (ST_SPEECH, SPCH_UNDER_ARREST, SL_3S, PRI_GAME_QUICK1);
	//right side status display
	ll_score_draw_ball ();

	//left side display
			//	DRAW HAND CUFFS
				bitmap_blit (cuffs_3_bits, 0, 16);
				sprintf_score (capture_simon_mode_last_score);
					font_render_string_right (&font_term6, 98, 21, sprintf_buffer);
					font_render_string_right (&font_halobold12, 98, 1, "CAUGHT");
				dmd_show_low ();
				task_sleep_sec (2);
	deff_exit ();
}//end of mode_effect_deff





void capture_simon_effect_deff(void) {
	U8 i = 0;
	U8 j = 0;
	__boolean TOGGLE = FALSE;
	__boolean TOGGLE_BOTTOM = FALSE;

	for (;;) {
		dmd_alloc_pair_clean();
//right side status display
		ll_score_draw_ball ();

//left side display
		bitmap_blit (cuffs_3_bits, 0, 16);
		if (++i % 2 == 0) { if (TOGGLE) TOGGLE = FALSE; else TOGGLE = TRUE; }//change TOGGLE once per second
		if (++j % 8 == 0) { if (TOGGLE_BOTTOM) TOGGLE_BOTTOM = FALSE; else TOGGLE_BOTTOM = TRUE; }//change TOGGLE once per second

		if (TOGGLE) font_render_string_right (&font_halobold12, 98, 1, "CATCH");
		else 		font_render_string_right (&font_halobold12, 98, 1, "SIMON");

		if (ballsave_test_active()) {
			sprintf ("%d BALL SAVE", ballsave_get_timer());
			font_render_string_center (&font_var5, 50, DMD_MED_CY_BOTTOM_LINE + 3, sprintf_buffer);
		}
		else
			if (TOGGLE_BOTTOM) {
			sprintf ("%d SEC", capture_simon_mode_timer, capture_simon_mode_shots_made);
			font_render_string_center (&font_var5, 72, DMD_SMALL_CY_3 + 1, sprintf_buffer);
			sprintf_score (capture_simon_mode_next_score);
			font_render_string_right (&font_term6, 98, 23, sprintf_buffer);
		}
		else {
			font_render_string_center (&font_term6, 72, DMD_MED_CY_2 + 2, "SHOOT");
			font_render_string_center (&font_term6, 72, DMD_MED_CY_BOTTOM_LINE, "ARROWS");
		}

		dmd_show_low ();
		task_sleep (TIME_1S);
	}//END OF ENDLESS LOOP
}//end of mode_effect_deff





/****************************************************************************
 *
 * randomize flag chosen
 *
 * we are using a very stupid and in-elegant
 * way of randomness - basically, we have a number
 * of predefined sets of flags and we randomly
 * pick one of those sets
 *
 * We do this mainly because there are certain combinations that
 * I do not want to be chosen
 ****************************************************************************/
void cap_simon_choose_random_flag_set(void) {
	U8 random_chooser;
	random_chooser = random_scaled(6);
	switch (random_chooser) {
	default:
	case 0:
		set_capture_simon_arrows_all_off ();
		set_capture_simon_arrows (CAPSIM_SIDERAMP + CAPSIM_LEFTRAMP + CAPSIM_CENTERRAMP); //123
		break;
	case 1:
		set_capture_simon_arrows_all_off ();
		set_capture_simon_arrows (CAPSIM_RIGHTRAMP + CAPSIM_LEFTRAMP + CAPSIM_CENTERRAMP); //124
		break;
	case 2:
		set_capture_simon_arrows_all_off ();
		set_capture_simon_arrows (CAPSIM_LEFTRAMP + CAPSIM_UNDERGRND + CAPSIM_CENTERRAMP); //125
		break;
	case 3:
		set_capture_simon_arrows_all_off ();
		set_capture_simon_arrows (CAPSIM_SIDERAMP + CAPSIM_CENTERRAMP + CAPSIM_RIGHTRAMP); //234
		break;
	case 4:
		set_capture_simon_arrows_all_off ();
		set_capture_simon_arrows (CAPSIM_SIDERAMP + CAPSIM_CENTERRAMP + CAPSIM_UNDERGRND); //235
		break;
	case 5:
		set_capture_simon_arrows_all_off ();
		set_capture_simon_arrows (CAPSIM_SIDERAMP +  CAPSIM_RIGHTRAMP + CAPSIM_UNDERGRND); //345
		break;
	}//end of switch
}//end of function

