/*
 * demolition man
 * cryoprison.c
 * 
 * written by James Cardona
 *
 * cryoprison multiball
 *
 *
 * */
/* CALLSET_SECTION (cryoprison, __machine5__) */


#include <freewpc.h>
#include "dm/global_constants.h"
#include <diverter.h> //autogenerated by divhold.ct
#include "shaker.h"
#include "ballsave.h"
#include "search.h"
#include <coin.h>



//local variables
score_t		cryoprison_score;
U8			cryoprison_jackpot_shots_made;
U8			cryoprison_MessageCounter;
U8 			cryoprison_jackpot_MessageCounter;
__boolean	cryoprison_start_music;
U8 cryoprison_display_counter;
U8 CRYO_TOGGLE;
U8 snake_pos;
__boolean	cryoprison_ballsave;
__boolean	is_cryoprison_running;


//external variables


//internally called function prototypes  --external found at protos.h



/****************************************************************************
 * multiball definition structure
 ***************************************************************************/
struct mb_mode_ops cryoprison_mode = {
	DEFAULT_MBMODE,
	//.update = , /* The update callback is invoked whenever the state of the multiball changes. */
	.music = MUS_MB,
	.deff_starting = DEFF_CRYOPRISON_START_EFFECT,
	.deff_running = DEFF_CRYOPRISON_EFFECT,
	//.deff_ending = ,
//.active_task = 				//	default => .active_task = mb_mode_active_task,
	.prio = PRI_MULTIBALL,		//default => .prio = PRI_NULL,
//.grace_period = 				//default => .grace_period = 500ms
};
//task_gid_t gid_running;
//task_gid_t gid_in_grace;


/****************************************************************************
 * initialize  and exit
 ***************************************************************************/
CALLSET_ENTRY (cryoprison, start_player) {
	score_zero(cryoprison_score);
	cryoprison_jackpot_shots_made = 0; //these need to be zeroed in before we enter the mode so bonus doesn't fake trigger
	cryoprison_start_music = FALSE;
}//end of function




CALLSET_ENTRY (cryoprison, start_ball) {
	is_cryoprison_running = FALSE;
	cryoprison_ballsave = FALSE;
}//end of function





/****************************************************************************
 * external event listeners
 ****************************************************************************/
CALLSET_ENTRY (cryoprison, music_refresh)  {
//	if (cryoprison_start_music)				music_request (SIREN, PRI_GAME_QUICK8);
//	else 									mb_mode_music_refresh (&cryoprison_mode);
	if (in_game && is_cryoprison_running)	music_request (MUS_MB_A, PRI_GAME_QUICK7);
}//end of function




CALLSET_ENTRY (cryoprison, display_update) {
	if (is_cryoprison_running)
			deff_start_bg (DEFF_CRYOPRISON_EFFECT, PRI_MULTIBALL);
}//end of function



CALLSET_ENTRY (cryoprison, end_ball, tilt) {
	if (is_cryoprison_running) {
		//kill the 5 sec trough recount
		callset_invoke (mb_trough_recount_timer_exit);

		mb_mode_end_ball (&cryoprison_mode);
		jackpot_reset();
		end_super_jackpot_reminder();

		if (!flag_test(FLAG_BACK_IN_THE_FRIDGE_ACTIVATED) )
			enable_back_in_the_fridge(); //at completion of our 4th MB we enable the wizard mode
	}
	is_cryoprison_running = FALSE;
	cryoprison_ballsave = FALSE;
}//end of function



//puts in grace period if set
CALLSET_ENTRY (cryoprison, single_ball_play) {
	if (is_cryoprison_running) {
		callset_invoke (mb_trough_recount_timer_exit);
		mb_mode_end_ball (&cryoprison_mode);
		end_super_jackpot_reminder();
//		combo_init();

		enable_back_in_the_fridge(); //at completion of our 4th MB we enable the wizard mode

		//this acts as kind of a grace period for the jackpots
		task_sleep_sec(3);
		is_cryoprison_running = FALSE;
		cryoprison_ballsave = FALSE;
		jackpot_reset();
		diverter_check();
		computer_award_light_recheck();
	}
}//end of function







/****************************************************************************
 *
 * body
 *
 ***************************************************************************/
__boolean get_cryoprison_running (void) {
		if (is_cryoprison_running) return TRUE;
		else return FALSE;
}//end of function



void cryoprison_ballsave_task (void) {

#ifdef CONFIG_DIFFICULTY_LEVEL
	task_sleep_sec(system_config.mb_ballsave);
#elif
	task_sleep_sec(5);
#endif
	cryoprison_ballsave = FALSE;
	task_exit();
}//end of function




void cryoprison_start_sounds (void) {
	U8 i;
	for(i = 0; i < 6; i++) {
		sound_start (ST_EFFECT, SIREN, SL_1S, PRI_GAME_QUICK3);
		task_sleep (TIME_500MS);
	}
	task_exit();
}//end of function





void cryoprison_start(U8 num) {
//	kill_combos();
	computer_light_temp_off();
	task_create_gid1 (GID_CRYOPRISON_START_NOISE, cryoprison_start_sounds);
	is_cryoprison_running = TRUE;
	cryoprison_display_counter = 0;
	CRYO_TOGGLE = 0;
	snake_pos = 0;
	cryoprison_ballsave = TRUE;
	mb_mode_start(&cryoprison_mode);
	multiball_started();//reset all MB start criteria for next time

	score_add (cryoprison_score, score_table[CRYOPRISON_MB_SCORE]);
	score (CRYOPRISON_MB_SCORE);

	deff_start (DEFF_CRYOPRISON_START_EFFECT);
	diverter_stop();//defined in divhold2.ct

	//LIGHTS
	leff_start (LEFF_MB_START);
			lamp_tristate_flash(LM_CRYOPRISON_MULTIBALL);
			task_sleep (TIME_2S);
			lamp_tristate_on (LM_CRYOPRISON_MULTIBALL);
			lamp_tristate_off (LM_FREEZE_1);
			lamp_tristate_off (LM_FREEZE_2);
			lamp_tristate_off (LM_FREEZE_3);
			lamp_tristate_off (LM_FREEZE_4);

	//SOUNDS
			U8 	cryoprison_SoundCounter;
			cryoprison_SoundCounter = random_scaled(2);//from kernal/random.c - pick number from 0 to 2
			if (cryoprison_SoundCounter == 0)
				sound_start (ST_SPEECH, SPCH_SIMON_SAYS_SLY, SL_4S, PRI_GAME_QUICK3);
			else
				sound_start (ST_SPEECH, SPCH_PHOENIX_SHORT, SL_4S, PRI_GAME_QUICK3);
	task_sleep (TIME_3S);
	sound_start (ST_SPEECH, SPCH_SIMON_SAYS, SL_4S, PRI_GAME_QUICK3);
	cryoprison_start_music = FALSE; //for to kill the music

	//serve balls
	set_ball_count (5);
	task_sleep (TIME_3S);

	task_create_gid1 (GID_CRYOPRISON_BALL_SAVE, cryoprison_ballsave_task);
	set_all_jackpots(); //all 6 lit
	//recount the trough every 5 secs - this is to handle situations
	//where too many drains in rapid succession cause the game to lose
	//count of live balls - this only happens during MB
	callset_invoke (mb_trough_recount_timer_start);

	//just in case - make sure this is running
	ball_search_monitor_start ();
	set_dm_mode2(CRYO_COMPLETED); //for BONUS
}//end of function



//jackpot shot
void cryoprison_jackpot_made(void) {
	score_add (cryoprison_score, score_table[CRYOPRISON_JP_MB_SCORE]);
	score (CRYOPRISON_JP_MB_SCORE);
	cryoprison_jackpot_shots_made++;

	if (system_config.disable_shaker == NO) {
		if (system_config.extra_shaker == YES) 	shaker_start (SHAKER_HALF_ON, 2);
		else									shaker_start (SHAKER_ONE_QUARTER_ON, 2);
	}//end of shaker call

	switch (cryoprison_jackpot_shots_made % 5) {
		case 1:	leff_start (LEFF_JACKPOT1); break;
		case 2:	leff_start (LEFF_JACKPOT2); break;
		case 3:	leff_start (LEFF_JACKPOT3); break;
		case 4:	leff_start (LEFF_JACKPOT4); break;
		default: leff_start (LEFF_JACKPOT); break;
	}
	deff_start (DEFF_CRYOPRISON_JACKPOT_EFFECT);
	choose_multiple_random_jackpot(3);

	if (DM_IN_CAB_TEST) {	start_super_jackpot_reminder(); }
	else			if (cryoprison_jackpot_shots_made % 5 == 0) 	start_super_jackpot_reminder();
}//end of function



void cryoprison_award_super_jackpot(void) {
	score_add (cryoprison_score, score_table[CRYOPRISON_SUPER_JP_MB_SCORE]);
	score (CRYOPRISON_SUPER_JP_MB_SCORE);

	if (system_config.disable_shaker == NO) {
		if (system_config.extra_shaker == YES) 	shaker_start (SHAKER_HALF_ON, 2);
		else									shaker_start (SHAKER_ONE_QUARTER_ON, 2);
	}//end of shaker call

	leff_start (LEFF_SUPER_JACKPOT);
	deff_start (DEFF_CRYOPRISON_SUPER_JACKPOT);
}//end of function





/****************************************************************************
 *
 * DMD display and sound effects
 *
 ****************************************************************************/
void cryoprison_super_jackpot_deff (void) {
	sound_start (ST_SPEECH, SPCH_CLOSE_ENOUGH, SL_2S, PRI_GAME_QUICK3);
				U16 fno;
				for (fno = IMG_SUPER_JACKPOT_START; fno <= IMG_SUPER_JACKPOT_END; fno += 2) {
					dmd_alloc_pair ();
					frame_draw(fno);
					dmd_show2 ();
					task_sleep (TIME_100MS);
				}
				for (fno = IMG_SUPER_JACKPOT_END; fno >= IMG_SUPER_JACKPOT_START; fno -= 2) {
					dmd_alloc_pair ();
					frame_draw(fno);
					dmd_show2 ();
					task_sleep (TIME_100MS);
				}
	speech_start (SPCH_SUPER_JACKPOT, SL_1S);
	task_sleep_sec (1);
	deff_exit ();
}//end of function




void cryoprison_animation_display_effect (U16 start_frame, U16 end_frame){
	U16 fno;
	for (fno = start_frame; fno <= end_frame; fno += 2) {
		dmd_alloc_pair ();
		frame_draw(fno);
		dmd_show2 ();
		task_sleep (TIME_100MS);
	}//end of inner loop
}



void cryoprison_frame_bitfade_fast (U16 frame){
	dmd_sched_transition (&trans_bitfade_fast);
	dmd_alloc_pair ();
	frame_draw(frame);
	dmd_show2 ();
	task_sleep (TIME_100MS);
}




void cryoprison_frame_with_words_display_steel_effect (U16 frame, U8 x, U8 y, char *words){
	dmd_alloc_pair_clean ();// Clean both pages
	dmd_map_overlay ();
	dmd_clean_page_low ();
		font_render_string_center (&font_halobold12, DMD_MIDDLE_X, DMD_BIG_CY_Top,  "CRYOPRISON");
		font_render_string_center (&font_halobold12, x, y, words);
	dmd_text_outline ();
	dmd_alloc_pair ();
	frame_draw(frame);
	dmd_overlay_outline ();
	dmd_show2 ();
	task_sleep (TIME_500MS);
}


void cryoprison_start_effect_deff(void) {
	U16 fno;
	dmd_alloc_pair_clean ();// Clean both pages
	cryoprison_animation_display_effect (IMG_CRYOPRISON_E1_START, IMG_CRYOPRISON_E1_END);

	cryoprison_frame_bitfade_fast(IMG_CRYOPRISON_E2_START);

	cryoprison_animation_display_effect (IMG_CRYOPRISON_E2_START, IMG_CRYOPRISON_E2_END);

	cryoprison_frame_bitfade_fast(IMG_CAPSIMON_C_START);

		dmd_alloc_pair_clean ();// Clean both pages
	for (fno = IMG_CAPSIMON_C_START; fno <= IMG_CAPSIMON_C_END; fno += 2) {
		dmd_map_overlay ();
		dmd_clean_page_low ();
			font_render_string_center (&font_halobold12, DMD_MIDDLE_X - 25, DMD_BIG_CY_Top, "CRYO");
			font_render_string_center (&font_halobold12, DMD_MIDDLE_X, DMD_BIG_CY_Bot, "MULTIBALL");
		dmd_text_outline ();
		dmd_alloc_pair ();
		frame_draw(fno);
		dmd_overlay_outline ();
		dmd_show2 ();
		task_sleep (TIME_100MS);
	}//end of inner loop
	task_sleep_sec (1);
	deff_exit ();
}//end of mode_effect_deff



void cryoprison_jackpot_sounds_task(void) {
	U8 			cryoprison_MessageCounter;
	cryoprison_MessageCounter = random_scaled(3);
	if (++cryoprison_jackpot_shots_made % 2 == 0) {
			switch (cryoprison_MessageCounter) {
				case 0: 	sound_start (ST_SPEECH, SPCH_DOUBLE_JACKPOT_WES, SL_2S, PRI_GAME_QUICK3); break;
				case 1: 	sound_start (ST_SPEECH, SPCH_DOUBLE_JACKPOT_SLY, SL_2S, PRI_GAME_QUICK3); break;
				case 2: 	sound_start (ST_SPEECH, SPCH_DOUBLE, SL_2S, PRI_GAME_QUICK3); break;
			}//end of switch
	}//end of if
	else {
		switch (cryoprison_MessageCounter) {
			case 0: 	sound_start (ST_SPEECH, SPCH_AHHHGGG, SL_2S, PRI_GAME_QUICK3); break;
			case 1: 	sound_start (ST_SPEECH, SPCH_JOHN_SCREAM, SL_2S, PRI_GAME_QUICK3); break;
			case 2: 	sound_start (ST_SPEECH, SPCH_UHHN, SL_2S, PRI_GAME_QUICK3); break;
		}//end of switch
	}//end of else
	task_sleep (TIME_500MS);
	sound_start (ST_EFFECT, FREEZE5, SL_1S, PRI_GAME_QUICK3);
	task_sleep (TIME_200MS);
	sound_start (ST_EFFECT, FREEZE5, SL_1S, PRI_GAME_QUICK3);
	task_sleep (TIME_200MS);
	sound_start (ST_EFFECT, FREEZE5, SL_1S, PRI_GAME_QUICK3);
	task_sleep (TIME_200MS);
	sound_start (ST_EFFECT, FREEZE5, SL_1S, PRI_GAME_QUICK3);
	task_sleep (TIME_200MS);
	sound_start (ST_EFFECT, EJECT, SL_2S, PRI_GAME_QUICK3);
	task_sleep (TIME_500MS);
	task_exit();
}//end of mode_effect_deff






void cryoprison_jackpot_effect_deff(void) {
	U16 fno;
	if (DM_IN_DMD_TEST) {		if (++cryoprison_jackpot_MessageCounter > 5) cryoprison_jackpot_MessageCounter = 0; }
	else  cryoprison_jackpot_MessageCounter = random_scaled(6);

	dmd_clean_page_high ();//
	dmd_clean_page_low ();//

	task_create_gid1 (GID_CRYOPRISON_JACKPOT_SOUND, cryoprison_jackpot_sounds_task);

	switch (cryoprison_jackpot_MessageCounter) {
		case 0:
			cryoprison_animation_display_effect (IMG_CAPSIMON_C_START, IMG_CAPSIMON_C_END);
			cryoprison_frame_with_words_display_steel_effect (IMG_CAPSIMON_C_END, DMD_MIDDLE_X, DMD_BIG_CY_Bot, "JACKPOT");
			break;
		case 1:
			cryoprison_animation_display_effect (IMG_CRYOPRISON_E2_START, IMG_CRYOPRISON_E2_END);
			cryoprison_frame_with_words_display_steel_effect (IMG_CRYOPRISON_E2_END, DMD_MIDDLE_X, DMD_BIG_CY_Bot, "JACKPOT");
			break;
		case 2:
			cryoprison_animation_display_effect (IMG_CRYOPRISON_E1_START, IMG_CRYOPRISON_E1_END);
			cryoprison_frame_with_words_display_steel_effect (IMG_CRYOPRISON_E1_END, DMD_MIDDLE_X, DMD_BIG_CY_Bot, "JACKPOT");
			break;
		case 3:
			cryoprison_animation_display_effect (IMG_DR_COCTEAU_B_START, IMG_DR_COCTEAU_B_END);
			cryoprison_frame_with_words_display_steel_effect (IMG_DR_COCTEAU_B_END, DMD_MIDDLE_X, DMD_BIG_CY_Bot, "JACKPOT");
			break;
		default:
		case 4: //5
			cryoprison_animation_display_effect (IMG_JACKPOT_START, IMG_JACKPOT_END);
			for (fno = IMG_JACKPOT_END; fno >= IMG_JACKPOT_START; fno -= 2) {
				dmd_alloc_pair ();
				frame_draw(fno);
				dmd_show2 ();
				task_sleep (TIME_100MS);
			}
			break;
		}//end of switch
	deff_exit ();
}//end of mode_effect_deff




void cryoprison_effect_deff (void) {
	for (;;) {
		dmd_clean_page_low ();
//right side status display
		ll_score_draw_ball ();

//left side display
		sprintf_score(current_score);
		font_render_string_center (&font_var5, 50, 13, sprintf_buffer);
		font_render_string_right (&font_halobold12, 80, 1, "CRYO");
		if (ballsave_test_active()) {
			sprintf ("%d BALL SAVE", ballsave_get_timer());
			font_render_string_center (&font_var5, 50, DMD_MED_CY_BOTTOM_LINE + 3, sprintf_buffer);
		}
		else {
			if (CRYO_TOGGLE == 0) 		{ sprintf ("15 MILLION"); font_render_string_right (&font_fixed6, 85, 21, sprintf_buffer); }
			else if (CRYO_TOGGLE == 1)	{ sprintf ("JACKPOT LIT"); font_render_string_right (&font_fixed6, 92, 21, sprintf_buffer); }
			else if (CRYO_TOGGLE == 2)	{
				sprintf ("%d JACKPOTS MADE", cryoprison_jackpot_shots_made);
				font_render_string_right (&font_var5, 85, 19, sprintf_buffer);

				if (get_is_super_jackpot_lit()) sprintf ("SUPER LIT");
				else sprintf ("SHOOT %d ENABLE SUPER", 5 - (cryoprison_jackpot_shots_made % 5) );
				font_render_string_right (&font_var5, 95, 26, sprintf_buffer);
			}
		}
		dmd_show_low ();
		task_sleep (TIME_1S);
		if (++cryoprison_display_counter % 5 == 0) { if (++CRYO_TOGGLE > 3) CRYO_TOGGLE = 0; } //change CRYO_TOGGLE once per second
	}//END OF ENDLESS LOOP
}//end of function

