/*
 * demolition man
 * demotime.c
 * 
 * written by James Cardona
 *
 * demotime multiball
 *
 *
 * */
/* CALLSET_SECTION (demotime, __machine5__) */


#include <freewpc.h>
#include "dm/global_constants.h"
#include <diverter.h> //autogenerated by divhold.ct
#include "search.h"
#include "shaker.h"
#include "ballsave.h"
#include <coin.h>


//constants
#define	DEMOTIME_EASY_GOAL  4
#define	DEMOTIME_HARD_GOAL  8

//local variables
U8			demotime_jackpot_shots_made;
U8			demotime_MessageCounter;
score_t		demotime_score;
__local__ U8			demotime_counter;
U8			demotime_goal;
__boolean	demotime_start_music;
U8	demotime_ballsave;
__boolean	is_demotime_running;
__boolean	is_demotime_starting; //this is for to hold the underground ball until display is done


//internally called function prototypes  --external found at protos.h


/****************************************************************************
 * multiball definition structure
 ***************************************************************************/
struct mb_mode_ops demotime_mode = {
	DEFAULT_MBMODE,
	//.update = , /* The update callback is invoked whenever the state of the multiball changes. */
	.music = MUS_MB_B,
//	.deff_starting = DEFF_DEMOTIME_START_EFFECT,
	.deff_running = DEFF_DEMOTIME_EFFECT,
	//.deff_ending = ,
//.active_task = 				//	default => .active_task = mb_mode_active_task,
	.prio = PRI_MULTIBALL,		//default => .prio = PRI_NULL,
//.grace_period = 				//default => .grace_period = 500ms
};
//task_gid_t gid_running;
//task_gid_t gid_in_grace;



/****************************************************************************
 * initialize  and exit
 ***************************************************************************/
CALLSET_ENTRY (demotime, start_player) {
	demotime_counter = 0;
	demotime_goal = DEMOTIME_EASY_GOAL;
	score_zero(demotime_score);
	demotime_jackpot_shots_made = 0; //these need to be zeroed in before we enter the mode so bonus doesn't fake trigger
	demotime_start_music = FALSE;
	lamp_tristate_off (LM_DEMO_TIME);

#ifdef CONFIG_DIFFICULTY_LEVEL
	demotime_goal = system_config.num2demotime;
#endif
	if (demotime_goal == 0)  flag_on(FLAG_IS_DEMOTIME_ENABLED);
	else flag_off(FLAG_IS_DEMOTIME_ENABLED);
}//end of function





CALLSET_ENTRY (demotime, start_ball) {
	is_demotime_running = FALSE;
	is_demotime_starting = FALSE;

	if (flag_test(FLAG_IS_DEMOTIME_ENABLED)) lamp_tristate_flash (LM_DEMO_TIME);
	else 									lamp_tristate_off (LM_DEMO_TIME);
}




/****************************************************************************
 * external event listeners
 ****************************************************************************/
CALLSET_ENTRY (demotime, music_refresh)  {
	if (in_game && demotime_start_music)				music_request (LOW_HORN, PRI_GAME_QUICK8);
	else if	(in_game && is_demotime_running)			music_request (MUS_MB_B, PRI_GAME_QUICK7);
}//end of function



CALLSET_ENTRY (demotime, display_update) {
	if (is_demotime_running)
		deff_start_bg (DEFF_DEMOTIME_EFFECT, PRI_MULTIBALL);
}//end of function



CALLSET_ENTRY (demotime, end_ball, tilt) {
	if (is_demotime_running) {
		//kill the 5 sec trough recount
		callset_invoke (mb_trough_recount_timer_exit);
		mb_mode_end_ball (&demotime_mode);
		jackpot_reset();
		end_super_jackpot_reminder();
		lamp_tristate_off (LM_DEMO_TIME);
		flag_off(FLAG_IS_DEMOTIME_ENABLED);
	}
	is_demotime_running = FALSE;
	demotime_ballsave = 0;
}//end of function



//puts in grace period if set, otherwise ends mode
CALLSET_ENTRY (demotime, single_ball_play) {
	if (is_demotime_running) {
		//kill the 5 sec trough recount
		callset_invoke (mb_trough_recount_timer_exit);
		mb_mode_end_ball (&demotime_mode);
		end_super_jackpot_reminder();
		lamp_tristate_off (LM_DEMO_TIME);
		flag_off(FLAG_IS_DEMOTIME_ENABLED);
	//	combo_init();

		//this acts as kind of a grace period for the jackpots
		task_sleep_sec(3);
		is_demotime_running = FALSE;
		jackpot_reset();
		diverter_check();
		computer_award_light_recheck();
	}//end of if
}//end of function





/****************************************************************************
 *
 * body
 *
 ***************************************************************************/
__boolean get_demotime_running (void) {
		if (is_demotime_running) return TRUE;
		else return FALSE;
}//end of function



__boolean get_demotime_starting (void) {
		if (is_demotime_starting) return TRUE;
		else return FALSE;
}//end of function



void demotime_ballsave_task (void) {
#ifdef CONFIG_DIFFICULTY_LEVEL
	U8 i;
	demotime_ballsave  = system_config.mode_ballsave;
	for (i = system_config.mb_ballsave; i > 0; i--) {
		task_sleep_sec(1);
		demotime_ballsave  -= 1;
	}
#elif
	U8 i;
	for (i = 5; i > 0; i--) {
		task_sleep_sec(1);
		demotime_ballsave  -= 1;
	}
#endif
	demotime_ballsave = 0;
	task_exit();
}//end of function


//MAKING ANY OF THE CLAW MODE SHOTS CALLS THIS
void demotime_increment (void) {
	if (++demotime_counter >= demotime_goal) {
		flag_on(FLAG_IS_DEMOTIME_ENABLED);
		deff_start (DEFF_DEMOTIME_INFO_EFFECT);//under /kernel/deff.c
		lamp_tristate_flash (LM_DEMO_TIME);
	}
}//end of function


//for testing
void demotime_increment_all (void) {
		flag_on(FLAG_IS_DEMOTIME_ENABLED);
		deff_start (DEFF_DEMOTIME_INFO_EFFECT);//under /kernel/deff.c
		lamp_tristate_flash (LM_DEMO_TIME);
}//end of function



//ONCE ENABLED IT IS STARTED BY A UNDERGROUND SHOT
void demotime_start(void) {
	ball_search_monitor_stop ();
//	kill_combos();
	computer_light_temp_off();
	demotime_ballsave  = system_config.mb_ballsave;
	demotime_start_music = TRUE;
	is_demotime_starting = TRUE;
	is_demotime_running = TRUE;
	flag_off(FLAG_IS_DEMOTIME_ENABLED);
	mb_mode_start(&demotime_mode);
	diverter_stop();//defined in divhold2.ct

	//LIGHTS
	lamp_tristate_on (LM_DEMO_TIME);

	//reset all start criteria for next time
	demotime_counter = 0;

	deff_start_sync(DEFF_DEMOTIME_START_EFFECT);

	set_all_jackpots();
	set_ball_count (5);

	task_create_gid1 (GID_DEMOTIME_BALL_SAVE, demotime_ballsave_task);
	sol_request_async(SOL_BOTTOM_POPPER);
	is_demotime_starting = FALSE;
	ball_search_monitor_start ();
	//recount the trough every 5 secs - this is to handle situations
	//where too many drains in rapid succession cause the game to lose
	//count of live balls - this only happens during MB
	callset_invoke (mb_trough_recount_timer_start);

	//turn off all claw lights to reset for next time
	reset_dm_mode(); //
	set_dm_mode2(DTIME_COMPLETED); //for BONUS
	lamp_tristate_off (LM_CLAW_CAPTURE_SIMON);
	lamp_tristate_off (LM_CLAW_ACMAG);
	lamp_tristate_off (LM_CLAW_SUPER_JETS);
	lamp_tristate_off (LM_CLAW_PRISON_BREAK);
	lamp_tristate_off (LM_CLAW_FREEZE); //this is the name of the light but it is really frenzy mode
}//end of function



//jackpot shot
void demotime_jackpot_made(void) {
	score_add (demotime_score, score_table[DEMOTIME_JP_MB_SCORE]);
	score (DEMOTIME_JP_MB_SCORE);

	if (system_config.disable_shaker == NO) {
		if (system_config.extra_shaker == YES) 	shaker_start (SHAKER_HALF_ON, 2);
		else									shaker_start (SHAKER_ONE_QUARTER_ON, 2);
	}//end of shaker call

	switch (random_scaled(5) ) {
		case 1:	leff_start (LEFF_JACKPOT1); break;
		case 2:	leff_start (LEFF_JACKPOT2); break;
		case 3:	leff_start (LEFF_JACKPOT3); break;
		case 4:	leff_start (LEFF_JACKPOT4); break;
		default: leff_start (LEFF_JACKPOT); break;
	}
	deff_start (DEFF_DEMOTIME_JACKPOT_EFFECT);
}//end of function



/****************************************************************************
 *
 * DMD display and sound effects
 *
 ****************************************************************************/
void demotime_animation_display_effect (U16 start_frame, U16 end_frame){
	U16 fno;
	for (fno = start_frame; fno <= end_frame; fno += 2) {
		dmd_alloc_pair ();
		frame_draw(fno);
		dmd_show2 ();
		task_sleep (TIME_100MS);
	}//end of inner loop
}



void demotime_frame_bitfade_fast (U16 frame){
	dmd_sched_transition (&trans_bitfade_fast);
	dmd_alloc_pair ();
	frame_draw(frame);
	dmd_show2 ();
	task_sleep (TIME_100MS);
}




void demotime_frame_with_words_display_steel_effect (U16 frame, U8 x, U8 y, char *words){
	dmd_alloc_pair_clean ();// Clean both pages
	dmd_map_overlay ();
	dmd_clean_page_low ();
		font_render_string_center (&font_halobold12, x, y, words);
	dmd_text_outline ();
	dmd_alloc_pair ();
	frame_draw(frame);
	dmd_overlay_outline ();
	dmd_show2 ();
	task_sleep (TIME_100MS);
}



void demotime_info_effect_deff(void) {
	dmd_clean_page_high ();
	dmd_clean_page_low ();
	font_render_string_center (&font_term6, DMD_MIDDLE_X, DMD_MED_CY_1, "SHOOT SUBWAY");
	font_render_string_center (&font_var5, DMD_MIDDLE_X, DMD_MED_CY_2, "FOR");
		font_render_string_center (&font_halobold12, DMD_MIDDLE_X, DMD_BIG_CY_Bot, "DEMO TIME");
	dmd_show_low();
	task_sleep_sec (3);
	deff_exit ();
}//end of mode_effect_deff




void demotime_start_effect_deff(void) {
	U8 i;
	for (i = 0; i < 2; i++) {
			sound_start (ST_ANY, SPECIAL_EFFECT, SL_1S, PRI_GAME_QUICK3);
			dmd_alloc_pair ();
			dmd_clean_page_low ();
			font_render_string_center (&font_halobold12, DMD_MIDDLE_X, DMD_BIG_CY_Top, "DEMO");
			font_render_string_center (&font_halobold12, DMD_MIDDLE_X, DMD_BIG_CY_Bot, "TIME");
			dmd_copy_low_to_high ();
			dmd_show_low ();
			dmd_invert_page (dmd_low_buffer);
			deff_swap_low_high (4, TIME_100MS);
			sound_start (ST_SAMPLE, EXPLOSION, SL_2S, PRI_GAME_QUICK3);
	}//end of i loop

	demotime_frame_bitfade_fast(IMG_FIGHT_A_START);
	sound_start (ST_SPEECH, SPCH_MUST_HAVE_HURT, SL_4S, PRI_GAME_QUICK3);
	sound_start (ST_SAMPLE, EXPLOSION, SL_2S, PRI_GAME_QUICK3);
	demotime_animation_display_effect (IMG_FIGHT_A_START, IMG_FIGHT_A_END);

	if (system_config.disable_shaker == NO) {
		if (system_config.extra_shaker == YES) 	shaker_start (SHAKER_HALF_ON, 2);
		else									shaker_start (SHAKER_ONE_QUARTER_ON, 2);
	}//end of shaker call

	demotime_frame_bitfade_fast(IMG_WASTELAND_A1_START);
	sound_start (ST_SPEECH, SPCH_IN_THIS_CENTURY, SL_4S, PRI_GAME_QUICK3);
	sound_start (ST_SAMPLE, EXPLOSION, SL_2S, PRI_GAME_QUICK3);
	demotime_animation_display_effect (IMG_WASTELAND_A1_START, IMG_WASTELAND_A1_END);

	if (system_config.disable_shaker == NO) {
		if (system_config.extra_shaker == YES) 	shaker_start (SHAKER_HALF_ON, 2);
		else									shaker_start (SHAKER_ONE_QUARTER_ON, 2);
	}//end of shaker call

	demotime_frame_bitfade_fast(IMG_CAPSIMON_C_START);
	sound_start (ST_SPEECH, SPCH_JOHN_SPARTAN, SL_4S, PRI_GAME_QUICK3);
	sound_start (ST_SAMPLE, EXPLOSION, SL_2S, PRI_GAME_QUICK3);
	demotime_animation_display_effect (IMG_CAPSIMON_C_START, IMG_CAPSIMON_C_END);


	if (system_config.disable_shaker == NO) {
		if (system_config.extra_shaker == YES) 	shaker_start (SHAKER_HALF_ON, 2);
		else									shaker_start (SHAKER_ONE_QUARTER_ON, 2);
	}//end of shaker call

	for (i = 0; i < 3; i++) {
			sound_start (ST_ANY, SPECIAL_EFFECT, SL_1S, PRI_GAME_QUICK3);
			dmd_alloc_pair ();
			dmd_clean_page_low ();
			font_render_string_center (&font_halobold12, DMD_MIDDLE_X, DMD_BIG_CY_Top, "DEMO");
			font_render_string_center (&font_halobold12, DMD_MIDDLE_X, DMD_BIG_CY_Bot, "TIME");
			dmd_copy_low_to_high ();
			dmd_show_low ();
			dmd_invert_page (dmd_low_buffer);
			deff_swap_low_high (5, TIME_100MS);
			sound_start (ST_SAMPLE, EXPLOSION, SL_2S, PRI_GAME_QUICK3);
	}//end of i loop

	if (system_config.disable_shaker == NO) {
		if (system_config.extra_shaker == YES) 	shaker_start (SHAKER_HALF_ON, 2);
		else									shaker_start (SHAKER_ONE_QUARTER_ON, 2);
	}//end of shaker call

	sound_start (ST_SPEECH, SPCH_DEMOLITION_MAN, SL_4S, PRI_GAME_QUICK3);
	task_sleep (TIME_200MS);
	demotime_start_music = FALSE; //kill the start music
	deff_exit ();
}//end of mode_effect_deff






U8 			demotime_SoundCounter;
void demotime_jackpot_sounds_task(void) {
	if (DM_IN_DMD_TEST) {	if (++demotime_SoundCounter > 5) demotime_SoundCounter = 0; }
	else			demotime_SoundCounter = random_scaled(6);

	switch (demotime_SoundCounter) {
		case 0: 	sound_start (ST_SPEECH, SPCH_TRESPASSING, SL_2S, PRI_GAME_QUICK3); break;
		case 1: 	sound_start (ST_SPEECH, SPCH_ARREST, SL_2S, PRI_GAME_QUICK3); break;
		case 2: 	sound_start (ST_SPEECH, SPCH_DREAMIN_KILLING_YOU, SL_2S, PRI_GAME_QUICK3); break;
	}//end of switch
	sound_start (ST_EFFECT, GUNSHOT_MUFFLED, SL_1S, PRI_GAME_QUICK3);
	task_sleep (TIME_200MS);
	sound_start (ST_EFFECT, GUNSHOT_MUFFLED, SL_1S, PRI_GAME_QUICK3);
	task_sleep (TIME_200MS);
	sound_start (ST_EFFECT, GUNSHOT_MUFFLED, SL_1S, PRI_GAME_QUICK3);
	task_sleep (TIME_200MS);
	sound_start (ST_EFFECT, GUNSHOT, SL_2S, PRI_GAME_QUICK3);
	task_sleep (TIME_500MS);
	switch (demotime_SoundCounter) {
		case 3: 	sound_start (ST_SPEECH, SPCH_JOHN_SCREAM, SL_2S, PRI_GAME_QUICK3); break;
		case 4: 	sound_start (ST_SPEECH, SPCH_DONT_WORRY, SL_2S, PRI_GAME_QUICK3); break;
		case 5: 	sound_start (ST_SPEECH, SPCH_KEEP_DREAMING, SL_2S, PRI_GAME_QUICK3); break;
	}//end of switch
	task_exit();
}//end of mode_effect_deff





U8 			demotime_MessageCounter;
void demotime_jackpot_effect_deff(void) {
	task_create_gid1 (GID_DEMOTIME_JACKPOT_SOUND, demotime_jackpot_sounds_task);
	U16 fno;
	for (fno = IMG_JACKPOT_START; fno <= IMG_JACKPOT_END; fno += 2) {
		dmd_alloc_pair ();
		frame_draw(fno);
		dmd_show2 ();
		task_sleep (TIME_100MS);
	}
	for (fno = IMG_JACKPOT_END; fno >= IMG_JACKPOT_START; fno -= 2) {
		dmd_alloc_pair ();
		frame_draw(fno);
		dmd_show2 ();
		task_sleep (TIME_100MS);
	}
	task_sleep (TIME_500MS);
	deff_exit ();
}//end of mode_effect_deff




void demotime_effect_deff (void) {
	U8 demotime_display_counter = 0;
	__boolean TOGGLE = FALSE;
	for (;;) {
		dmd_clean_page_low ();
//right side status display
		ll_score_draw_ball ();

//left side display
		sprintf_score(current_score);
		font_render_string_center (&font_var5, 50, 13, sprintf_buffer);
		font_render_string_right (&font_halobold12, 88, 1, "D TIME");
		if (demotime_ballsave) {
			sprintf ("%d BALL SAVE", demotime_ballsave);
			font_render_string_center (&font_var5, 50, DMD_MED_CY_BOTTOM_LINE + 3, sprintf_buffer);
		}
		else
		if (TOGGLE) 		{ sprintf ("15 MILLION"); font_render_string_right (&font_fixed6, 85, 21, sprintf_buffer); }
		else 				{ sprintf ("JACKPOT LIT"); font_render_string_right (&font_fixed6, 92, 21, sprintf_buffer); }
		dmd_show_low ();
		task_sleep (TIME_1S);

		demotime_display_counter++;
		if (demotime_display_counter % 5 == 0) { if (TOGGLE) TOGGLE = FALSE; else TOGGLE = TRUE; }//change TOGGLE once per second
	}//END OF ENDLESS LOOP
}//end of function

