/*
 * demolition man
 * explode.c
 *
 * written by James Cardona
 *
 * Location Description:
 * Retina Scan: This is the leftmost shot of the game. The ball passes through a gate
 * and into an eject that feeds the left inlane.
 * If hit hard enough through the gate, it will hit the captive eyeball.
 *
 * Scoring Description: (original game)
 * Shots that knock the captive eyeball into the upper target award the Retina Scan value.
 * The Jet Bumpers increase the Retina Value.(eyeball)
 * It starts at 5M and goes up 100K per jet.
 *
 * At certain numbers of Retina Scans hits, Explode Hurry Up is activated.
 * It takes 1 hit for the first Hurry-Up, four for the next on the easiest level.
 *
 * All four Explode ramps are lit at a value of 15M that begins counting down.
 * Hit any explode lamp to collect and add 10M to the value for the next Explode shot.
 * The round times out when the countdown reaches 5M (or higher if you've collected a few of the shots).
 * An extra ball is lit at three Retina Scans.
 *
 *
 * Scoring Description: (my rules)
 * same as above except explode mode times out after 30 seconds or ball drain
 * and eyeball shot can be hit in addition to explode arrows
 *
 * estimate of average explode mode score: 80 million to 120 million
 * estimate of average eyeball score: 10 million to 20 million
 *
 */
/* CALLSET_SECTION (explode, __machine2__) */

#include <freewpc.h>
#include "dm/global_constants.h"
#include <diverter.h> //autogenerated by divhold.ct
#include <ballsave.h>
#include "shaker.h"
#include <coin.h>


//constants
#define EXPLODE_TIMER_DEFAULT  43


//local variables
U8				explode_MessageCounter;
U8 				explode_temp_counter; //temporary counter
U8 				explode_SoundCounter;
U8 				explode_mode_timer;
U8 				explode_mode_shots_made;//number of times an explode is hit
score_t 		explode_mode_score;
score_t 		explode_mode_last_score;
score_t 		explode_mode_temp_score;
score_t 		explode_mode_display_score;
__boolean		is_explode_running;
U8		explode_ballsave;


//external variables


//internally called function prototypes  --external found at protos.h
void explode_mode_init (void);
void explode_mode_expire (void);
void explode_mode_exit (void);
void explode_reset (void);
void player_explode_reset (void);
void explode_ballsave_task (void);



/****************************************************************************
 * mode definition structure
 ***************************************************************************/
struct timed_mode_ops explode_mode = {
	DEFAULT_MODE,
	.init = explode_mode_init,
	.exit = explode_mode_expire,
	.gid = GID_EXPLODE_MODE_RUNNING,
	.music = MUS_MD_EXPLODE,
	.deff_starting = DEFF_EXPLODE_START_EFFECT,
	.deff_running = DEFF_EXPLODE_EFFECT,
//	.deff_ending = DEFF_EXPLODE_END,
	.prio = PRI_GAME_MODE5,
	.init_timer = 43, //make sure to set EXPLODE_TIMER_DEFAULT to the same value
	.timer = &explode_mode_timer,
	.grace_timer = 2, //DEFAULT IS 2
//	.pause = system_timer_pause,
};




/****************************************************************************
 * initialize  and exit
 ***************************************************************************/
void player_explode_reset (void) {
	is_explode_running = FALSE;
	explode_ballsave = 0;
	explode_mode_shots_made = 0;
	explode_SoundCounter = 0;
}//end of function



void explode_reset (void) {
	is_explode_running = FALSE;
	explode_ballsave = 0;
}//end of function



void explode_mode_init (void) {
	//check if explode is already running and do these things at first start only
	if (!is_explode_running) {
		explode_mode_shots_made = 0;

		score_zero(explode_mode_score);
	} //otherwise we are already in explode so add time to timer
	else timed_mode_add (&explode_mode, 10);
	//do all the rest in either case
	explode_MessageCounter = 0;
	is_explode_running = TRUE;

	//start the ball save timer
	explode_ballsave = system_config.mode_ballsave;
	task_create_gid1 (GID_EXPLODE_BALLSAVE_TIMER, explode_ballsave_task);

	if ( (explode_SoundCounter++ % 2) == 0 )//check if even
		sound_start (ST_SPEECH, SPCH_EXPLODE_ACTIVATED, SL_4S, PRI_GAME_QUICK4);
	else
		sound_start (ST_SPEECH, SPCH_EXPLODE_HURRYUP, SL_4S, PRI_GAME_QUICK4);
	score(EXPLODE_START);
	score_add (explode_mode_score, score_table[SC_15M]);

	task_sleep(TIME_3S);//wait for served ball so that explode made not trigger by it
	//leave these here to take care of end of grace period conditions
	activate_explode_inserts_ramps();
	activate_explode_inserts_orbits();
	set_dm_mode(EXPLODE_COMPLETED);
}//end of function




//this is an exit on timeout, ball still in play
void explode_mode_expire (void) {
	is_explode_running = FALSE;
	explode_ballsave = 0;
	deactivate_explode_inserts_ramps();
	deactivate_explode_inserts_orbits();
	diverter_check();
}//end of function



//this is an exit on end of ball
//must do this differently to prevent excessive cycling of diverter which
//tends to blow fuses
void explode_mode_exit (void) {
	is_explode_running = FALSE;
	explode_ballsave = 0;
	deactivate_explode_inserts_ramps();
	deactivate_explode_inserts_orbits();

	timed_mode_end2(&explode_mode);
}//end of function


/*
//if a ball drains during the mode and with time still on the ballsave timer - send it back in play
ALLSET_BOOL_ENTRY (explode, ball_drain) { //thrown by device.c
	if	(is_explode_running && explode_ballsave)	{
		sound_start (ST_SAMPLE, EXPLOSION, SL_2S, PRI_GAME_QUICK1);
		serve_ball_auto ();
		sound_start (ST_SAMPLE, EXPLOSION, SL_2S, PRI_GAME_QUICK1);
		return FALSE; //this is not a valid drain, don't count it
	}
	else return TRUE; //this is a valid drain
}//end of callset
*/







/****************************************************************************
 * external event listeners
 ****************************************************************************/
CALLSET_ENTRY (explode, music_refresh)  { if (in_game) timed_mode_music_refresh (&explode_mode); }
CALLSET_ENTRY (explode, end_ball, tilt)	{ if (timed_mode_running_p(&explode_mode) ) explode_mode_exit(); }
CALLSET_ENTRY (explode, display_update) { if (in_game && !flag_test(FLAG_VIDEO_MODE_RUNNING) )	 timed_mode_display_update (&explode_mode); }
CALLSET_ENTRY (explode, start_player) 	{ player_explode_reset(); }
CALLSET_ENTRY (explode, start_ball) 	{ explode_reset(); }

/****************************************************************************
 *
 * body
 *
 ***************************************************************************/
__boolean is_explode_mode_running (void) {
		if (is_explode_running) return TRUE;
		else return FALSE;
}//end of function



void explode_ballsave_task (void) {
#ifdef CONFIG_DIFFICULTY_LEVEL
	U8 i;
	explode_ballsave = system_config.mb_ballsave;
	for (i = system_config.mb_ballsave; i > 0; i--) {
		task_sleep_sec(1);
		explode_ballsave -= 1;
	}
#elif
	U8 i;
	for (i = 5; i > 0; i--) {
		task_sleep_sec(1);
		explode_ballsave -= 1;
	}
#endif
	explode_ballsave = 0;
	task_exit();
}//end of function


void start_explode(void) {
	huxley_increment();
	timed_mode_begin (&explode_mode);//start explode mode
}//end of function




void explode_lights_task (void) {
	U8 i;
	sound_start (ST_SAMPLE, EXPLOSION, SL_1S, PRI_GAME_QUICK2);
	for (i = 0; i < 5; i++) {
		flasher_pulse (FLASH_DIVERTER_FLASHER); //FLASH followed by name of flasher in caps
		task_sleep (TIME_33MS);
		flasher_pulse (FLASH_LEFT_RAMP_UP);
		task_sleep (TIME_33MS);
		flasher_pulse (FLASH_RIGHT_RAMP_UP);
		task_sleep (TIME_133MS);
		if (i % 2 == 0) sound_start (ST_SAMPLE, EXPLOSION, SL_1S, PRI_GAME_QUICK2);
	}
	task_sleep (TIME_133MS);
	sound_start (ST_SAMPLE, EXPLOSION, SL_1S, PRI_GAME_QUICK2);
	task_exit();
}// end of function




void explode_made(void) {
//	task_create_gid1 (GID_EXPLODE_LIGHTS, explode_lights_task);
	++explode_mode_shots_made;
	//score xx million counting down to 0 at end of mode  + 1 million for # of explodes hit
	score_zero(explode_mode_temp_score);
	score_add (explode_mode_temp_score, score_table[EXPLODE_SCORE]);
	score_mul (explode_mode_temp_score, explode_mode_timer);

	score_zero(explode_mode_last_score);
	score_add (explode_mode_last_score, explode_mode_temp_score);
	score_long (explode_mode_temp_score);
	score_add (explode_mode_score, explode_mode_temp_score);

	if (system_config.disable_shaker == NO) {
		if (system_config.extra_shaker == YES) 	shaker_start (SHAKER_HALF_ON, 2);
		else									shaker_start (SHAKER_ONE_QUARTER_ON, 2);
	}//end of shaker call

	leff_start (LEFF_EXPLODE);
	deff_start (DEFF_EXPLODE_HIT_EFFECT);
}//end of function



/****************************************************************************
 *
 * DMD display and sound effects
 *
 ****************************************************************************/
void explode_start_effect_deff(void) {
	U8 count = 5;
	dmd_alloc_pair_clean ();
	dmd_draw_thin_border (dmd_low_buffer);
		font_render_string_center (&font_halobold14, DMD_MIDDLE_X, DMD_BIG_CY_Cent, "EXPLODE");
	/* low = text, high = blank */
	while (--count > 0){
		dmd_show2 ();
		task_sleep (TIME_100MS);

		dmd_flip_low_high ();
		dmd_show2 ();
		task_sleep (TIME_100MS);

		dmd_show_high ();
		task_sleep (TIME_200MS);

		dmd_show2 ();
		task_sleep (TIME_100MS);
		dmd_flip_low_high ();

		if (system_config.disable_shaker == NO) {
			if (system_config.extra_shaker == YES) 	shaker_start (SHAKER_HALF_ON, 2);
			else									shaker_start (SHAKER_ONE_QUARTER_ON, 1);
		}//end of shaker call
	}
	deff_exit ();
}//end of mode_effect_deff



void explode_hit_effect_deff(void) {
	U16 fno;
	sound_start (ST_SAMPLE, EXPLOSION, SL_2S, PRI_GAME_QUICK1);
	dmd_alloc_pair_clean ();// Clean both pages

	for (fno = IMG_MARIO_EXPLODE_START; fno <= IMG_MARIO_EXPLODE_END; fno += 2) {
		dmd_alloc_pair_clean ();// Clean both pages
		frame_draw(fno);
		dmd_show2 ();
		task_sleep (TIME_100MS);
	}
	dmd_alloc_pair_clean ();// Clean both pages
	dmd_map_overlay ();
	dmd_clean_page_low ();
	font_render_string_center (&font_var5, DMD_MIDDLE_X, DMD_SMALL_CY_1, "EXPLODE");

	switch (++explode_MessageCounter % 4) {
		default:
		case 0: font_render_string_center (&font_halobold14, DMD_MIDDLE_X, DMD_BIG_CY_Bot, "BANG"); 	break;
		case 1: font_render_string_center (&font_halobold14, DMD_MIDDLE_X, DMD_BIG_CY_Bot, "BOOOYAH"); 	break;
		case 2: font_render_string_center (&font_halobold14, DMD_MIDDLE_X, DMD_BIG_CY_Bot, "BOOM"); 	break;
		case 3: font_render_string_center (&font_halobold14, DMD_MIDDLE_X, DMD_BIG_CY_Bot, "POW"); 		break;
	}//end of switch

	dmd_text_outline ();
	dmd_alloc_pair ();
	frame_draw(IMG_MARIO_EXPLODE_END);
	dmd_overlay_outline ();
	dmd_show2 ();
	task_sleep (TIME_500MS);
	deff_exit ();
}//end of mode_effect_deff





void explode_effect_deff(void) {
	U8 i;
	for (;;) {
		dmd_clean_page_low ();
//right side status display
		ll_score_draw_ball ();

//left side display
		score_zero(explode_mode_display_score);
		score_add (explode_mode_display_score, score_table[EXPLODE_SCORE]);
		score_mul (explode_mode_display_score, explode_mode_timer);
		sprintf_score (explode_mode_display_score);
		font_render_string_center (&font_var5, 50, 15, sprintf_buffer);
		font_render_string_right (&font_halobold12, 98, 1, "EXPLODE");

		if (explode_ballsave) {
			sprintf ("%d BALL SAVE", explode_ballsave );
			font_render_string_center (&font_var5, 50, DMD_MED_CY_BOTTOM_LINE + 3, sprintf_buffer);
		}
		else
		for (i = 5; i < (95 - explode_mode_timer * 2 ); i++) {
			sprintf ("I");
			font_render_string_left (&font_var5, i, DMD_SMALL_CY_4+3, sprintf_buffer);
		}//end of for loop

		dmd_show_low ();
		task_sleep (TIME_1S);//score goes down by second so update every xxms is plenty soon enough
	}//END OF ENDLESS LOOP
}//end of mode_effect_deff



