/*
 * demolition man
 * fortress.c
 * 
 * written by James Cardona
 *
 * handles the lock freezes and the trigger of multiballs
 *
 *
 * */
/* CALLSET_SECTION (fortress, __machine3__) */


#include <freewpc.h>
#include "dm/global_constants.h"
#include <diverter.h> //autogenerated by divhold.ct
#include "ballsave.h"
#include "shaker.h"
#include "search.h"
#include <coin.h>


//local variables
score_t		fortress_score;
U8			fortress_jackpot_shots_made;
U8			fortress_MessageCounter;
U8 			fortress_display_counter;
U8 			FORT_TOGGLE;
__boolean	is_fortress_running;
U8	fortress_ballsave;


//external variables


//internally called function prototypes  --external found at protos.h



/****************************************************************************
 * multiball definition structure
 ***************************************************************************/


struct mb_mode_ops fortress_mode = {
	DEFAULT_MBMODE,
	//.update = , /* The update callback is invoked whenever the state of the multiball changes. */
	.music = MUS_MB, //handled below
	.deff_starting = DEFF_FORTRESS_START_EFFECT,
	.deff_running = DEFF_FORTRESS_EFFECT,
	//.deff_ending = ,
//.active_task = 				//	default => .active_task = mb_mode_active_task,
	.prio = PRI_MULTIBALL,		//default => .prio = PRI_NULL,
//.grace_period = 				//default => .grace_period = 500ms

	//	.gid_running = GID_FORTRESS_MB,
	//.gid_in_grace = , //of type task_gid_t
};


/****************************************************************************
 * initialize  and exit
 ***************************************************************************/
CALLSET_ENTRY (fortress, start_ball) {
	is_fortress_running = FALSE;
	fortress_ballsave = 0;
}



CALLSET_ENTRY (fortress, start_player) {
	score_zero(fortress_score);
	fortress_jackpot_shots_made = 0; //these need to be zeroed in before we enter the mode so bonus doesn't fake trigger
	fortress_ballsave = 0;
}//end of function






/****************************************************************************
 * external event listeners
 ****************************************************************************/
CALLSET_ENTRY (fortress, music_refresh)  {
	if (in_game && is_fortress_running)	music_request (MUS_MB_B, PRI_GAME_QUICK7);
}//end of function



CALLSET_ENTRY (fortress, display_update) {
	if (is_fortress_running) deff_start_bg (DEFF_FORTRESS_EFFECT, PRI_MULTIBALL);
}//end of function



CALLSET_ENTRY (fortress, end_ball, tilt) {
	if (is_fortress_running) {
		//kill the 5 sec trough recount
		callset_invoke (mb_trough_recount_timer_exit);

		mb_mode_end_ball (&fortress_mode);
		jackpot_reset();
		end_super_jackpot_reminder();
	}
	is_fortress_running = FALSE;
	fortress_ballsave = 0;
}//end of function



//Also puts in grace period if set
CALLSET_ENTRY (fortress, single_ball_play) {
	//kill the 5 sec trough recount
	callset_invoke (mb_trough_recount_timer_exit);

	//fortress is only a 2 ball MB so there is a possibility of
	//getting a quick drain and immediately losing the MB here
	//
	//incorporating a ball save here makes sense, but if the ball save
	//task gets stuck because the task ended abnormally, which has
	//happened, then we are stuck in a MB infinite loop
//	if (is_fortress_running && !fortress_ballsave ) {
	if (is_fortress_running) {
				mb_mode_end_ball (&fortress_mode);
				end_super_jackpot_reminder();
	//			combo_init();
				//this acts as kind of a grace period for the jackpots
				task_sleep_sec(3);
				is_fortress_running = FALSE;
				jackpot_reset();
				diverter_check();
				computer_award_light_recheck();
	}
}//end of function





/****************************************************************************
 *
 * body
 *
 ***************************************************************************/
__boolean get_fortress_running (void) {
		if (is_fortress_running) return TRUE;
		else return FALSE;
}//end of function




void fortress_ballsave_task (void) {
#ifdef CONFIG_DIFFICULTY_LEVEL
	U8 i;
	fortress_ballsave  = system_config.mb_ballsave;
	for (i = system_config.mb_ballsave; i > 0; i--) {
		task_sleep_sec(1);
		fortress_ballsave  -= 1;
	}
#elif
	U8 i;
	for (i = 5; i > 0; i--) {
		task_sleep_sec(1);
		fortress_ballsave  -= 1;
	}
#endif
	fortress_ballsave  = 0;
	task_exit();
}//end of function




void fortress_start_sounds (void) {
	U8 i;
	for(i = 0; i < 8; i++) {
		sound_start (ST_EFFECT, HELICOPTER, SL_1S, PRI_GAME_QUICK3);
		task_sleep (TIME_500MS);
	}
	task_exit();
}//end of function





void fortress_start(U8 num) {
	computer_light_temp_off();
	is_fortress_running = TRUE;
	task_create_gid1 (GID_FORTRESS_START_NOISE, fortress_start_sounds);
	fortress_display_counter = 0;
	FORT_TOGGLE = 0;
	fortress_ballsave  = system_config.mb_ballsave;

	mb_mode_start(&fortress_mode);
	score_add (fortress_score, score_table[FORTRESS_MB_SCORE]);
	score (FORTRESS_MB_SCORE);

	if (!in_tilt) deff_start (DEFF_FORTRESS_START_EFFECT);
	multiball_started();//reset all MB start criteria for next time
	diverter_stop();//defined in divhold2.ct

	//LIGHTS
	if (!in_tilt) {
		leff_start (LEFF_MB_START);
			lamp_tristate_flash(LM_FORTRESS_MULTIBALL);
			task_sleep (TIME_2S);
			lamp_tristate_on (LM_FORTRESS_MULTIBALL);
			lamp_tristate_off (LM_FREEZE_1);
			lamp_tristate_off (LM_FREEZE_2);
			lamp_tristate_off (LM_FREEZE_3);
			lamp_tristate_off (LM_FREEZE_4);
	}
	//SOUNDS
	if (!in_tilt) {
			U8 	fortress_SoundCounter;
			fortress_SoundCounter = random_scaled(2);//from kernal/random.c - pick number from 0 to 2
			if (fortress_SoundCounter == 0)
				sound_start (ST_SPEECH, SPCH_SOMETHING_RIGHT_PREV_LIFE, SL_4S, PRI_GAME_QUICK3);
			else
				sound_start (ST_SPEECH, SPCH_SEND_MANIAC, SL_4S, PRI_GAME_QUICK3);
			task_sleep (TIME_3S);
	}

	//serve balls
	if (!in_tilt) {
		if (num + live_balls >= 5) set_ball_count (5);
		else set_ball_count (num + live_balls);
		//task_sleep (TIME_3S);
		set_all_jackpots(); //all 6 lit

		//start the ball save timer
		task_create_gid1 (GID_FORTRESS_BALLSAVE_TIMER, fortress_ballsave_task);
		//recount the trough every 5 secs - this is to handle situations
		//where too many drains in rapid succession cause the game to lose
		//count of live balls - this only happens during MB
		callset_invoke (mb_trough_recount_timer_start);
	}
	//just in case - make sure this is running
	ball_search_monitor_start ();
	set_dm_mode2(FORTRESS_COMPLETED); //for BONUS
}//end of function




/*******************
 * start with all jackpot shots lit and as shots are made decrease # of lights lit
 ******************/
void fortress_jackpot_made(void) {
	++fortress_jackpot_shots_made;
	score_add (fortress_score, score_table[FORTRESS_JP_MB_SCORE]);
	score (FORTRESS_JP_MB_SCORE);

	if (system_config.disable_shaker == NO) {
		if (system_config.extra_shaker == YES) 	shaker_start (SHAKER_HALF_ON, 2);
		else									shaker_start (SHAKER_ONE_QUARTER_ON, 2);
	}//end of shaker call

	switch (fortress_jackpot_shots_made % 5) {
		case 1:	leff_start (LEFF_JACKPOT1); break;
		case 2:	leff_start (LEFF_JACKPOT2); break;
		case 3:	leff_start (LEFF_JACKPOT3); break;
		case 4:	leff_start (LEFF_JACKPOT4); break;
		default: leff_start (LEFF_JACKPOT); break;
	}
	deff_start (DEFF_FORTRESS_JACKPOT_EFFECT);

	if 		(fortress_jackpot_shots_made < 2)	choose_multiple_random_jackpot (3); //after 1 made, at most 3 lit
	else if (fortress_jackpot_shots_made < 4)	choose_multiple_random_jackpot (2); //for 2nd and 3rd, at most 2 lit
	else 										choose_random_jackpot ();			//for rest, only 1 lit

	if (DM_IN_CAB_TEST) {	start_super_jackpot_reminder(); }
	else
		if (fortress_jackpot_shots_made % 5 == 0) 	start_super_jackpot_reminder();
}//end of function




void fortress_award_super_jackpot(void) {
	score_add (fortress_score, score_table[FORTRESS_SUPER_JP_MB_SCORE]);
	score (FORTRESS_SUPER_JP_MB_SCORE);

	if (system_config.disable_shaker == NO) {
		if (system_config.extra_shaker == YES) 	shaker_start (SHAKER_HALF_ON, 2);
		else									shaker_start (SHAKER_ONE_QUARTER_ON, 2);
	}//end of shaker call

	leff_start (LEFF_SUPER_JACKPOT);
	deff_start(DEFF_FORTRESS_SUPER_JACKPOT);
}//end of function





/****************************************************************************
 *
 * DMD display and sound effects
 *
 ****************************************************************************/
void fortress_animation_display_effect (U16 start_frame, U16 end_frame){
	U16 fno;
	for (fno = start_frame; fno <= end_frame; fno += 2) {
		dmd_alloc_pair ();
		frame_draw(fno);
		dmd_show2 ();
		task_sleep (TIME_100MS);
	}//end of inner loop
}



void fortress_frame_bitfade_fast (U16 frame){
	dmd_sched_transition (&trans_bitfade_fast);
	dmd_alloc_pair ();
	frame_draw(frame);
	dmd_show2 ();
	task_sleep (TIME_100MS);
}



void fortress_frame_with_words_display_steel_effect (U16 frame, U8 x, U8 y, char *words){
	dmd_alloc_pair_clean ();// Clean both pages
	dmd_map_overlay ();
	dmd_clean_page_low ();
		font_render_string_center (&font_halobold12, DMD_MIDDLE_X, DMD_BIG_CY_Top,  "FORTRESS");
		font_render_string_center (&font_halobold12, x, y, words);
	dmd_text_outline ();
	dmd_alloc_pair ();
	frame_draw(frame);
	dmd_overlay_outline ();
	dmd_show2 ();
	task_sleep (TIME_500MS);
}




void fortress_start_effect_deff(void) {
	dmd_alloc_pair_clean();
	fortress_animation_display_effect (IMG_FORT_START_MARIO_START, IMG_FORT_START_MARIO_END);
	fortress_frame_with_words_display_steel_effect (IMG_FORT_START_MARIO_END, DMD_MIDDLE_X, DMD_BIG_CY_Bot, "MULTIBALL");
	task_sleep_sec (1);
	deff_exit ();
}//end of mode_effect_deff





void fortress_jackpot_sounds_task(void) {
	U8 			fortress_MessageCounter;
	if (system_config.swear_sounds == YES) {
		//this doubles the chance that a swear would occur
		fortress_MessageCounter = random_scaled(11);
		if (fortress_MessageCounter >= 8) fortress_MessageCounter -= 3;
	}
	else if (system_config.extra_sounds == YES) {
		fortress_MessageCounter = random_scaled(5);
	}
	else {
		fortress_MessageCounter = random_scaled(3);
	}

	sound_start (ST_EFFECT, GUNSHOT_MUFFLED, SL_100MS, PRI_GAME_QUICK3);
	task_sleep (TIME_200MS);
	sound_start (ST_EFFECT, GUNSHOT_MUFFLED, SL_100MS, PRI_GAME_QUICK3);
	task_sleep (TIME_200MS);
	sound_start (ST_EFFECT, RICOCHET, SL_100MS, PRI_GAME_QUICK3);
	task_sleep (TIME_500MS);

	switch (fortress_MessageCounter) {
		case 0: 	sound_start (ST_SPEECH, SPCH_AHHHGGG, SL_2S, PRI_GAME_QUICK3); break;
		case 1: 	sound_start (ST_SPEECH, SPCH_JOHN_SCREAM, SL_2S, PRI_GAME_QUICK3); break;
		case 2: 	sound_start (ST_SPEECH, SPCH_UHHN, SL_2S, PRI_GAME_QUICK3); break;

		case 3: 	sound_start (ST_SPEECH, SPCH_LOVE_MULTIPLE_JACKPOTS_GIRL, SL_2S, PRI_GAME_QUICK3); break;
		case 4: 	sound_start (ST_SPEECH, SPCH_FEEL_LIKE_A_PINBALL_SLY, SL_2S, PRI_GAME_QUICK3); break;

		case 5: 	sound_start (ST_SPEECH, SPCH_VLGR_SHT_SANDWICH_SLY, SL_2S, PRI_GAME_QUICK3); break;
		case 6: 	sound_start (ST_SPEECH, SPCH_VLGR_KISS_MY_AS2_SLY, SL_2S, PRI_GAME_QUICK3); break;
		case 7: 	sound_start (ST_SPEECH, SPCH_VLGR_HOLY_SHT_SIMON, SL_2S, PRI_GAME_QUICK3); break;
	}//end of switch

	sound_start (ST_EFFECT, GUNSHOT_MUFFLED, SL_100MS, PRI_GAME_QUICK3);
	task_sleep (TIME_200MS);
	sound_start (ST_EFFECT, GUNSHOT_MUFFLED, SL_100MS, PRI_GAME_QUICK3);
	task_sleep (TIME_200MS);
	sound_start (ST_EFFECT, GUNSHOT_MUFFLED, SL_100MS, PRI_GAME_QUICK3);
	task_sleep (TIME_200MS);
	sound_start (ST_EFFECT, RICOCHET, SL_200MS, PRI_GAME_QUICK3);
	task_sleep (TIME_200MS);

	if (fortress_jackpot_shots_made % 2 == 0) {
			switch (fortress_MessageCounter) {
				case 0: 	sound_start (ST_SPEECH, SPCH_DOUBLE_JACKPOT_WES, SL_2S, PRI_GAME_QUICK3); break;
				case 1: 	sound_start (ST_SPEECH, SPCH_DOUBLE_JACKPOT_SLY, SL_2S, PRI_GAME_QUICK3); break;
				case 2: 	sound_start (ST_SPEECH, SPCH_DOUBLE, SL_2S, PRI_GAME_QUICK3); break;
			}//end of switch
	}//end of if

	task_exit();
}//end of mode_effect_deff




void fortress_jackpot_effect_deff(void) {
	U16 fno;

	if (DM_IN_DMD_TEST) {	if (++fortress_MessageCounter > 4) fortress_MessageCounter = 0;} //for testing
	else fortress_MessageCounter = random_scaled(5);
	dmd_alloc_pair_clean();
	task_create_gid1 (GID_FORTRESS_JACKPOT_SOUND, fortress_jackpot_sounds_task);

	switch (fortress_MessageCounter) {
		case 0:
			fortress_animation_display_effect (IMG_FORTRESS_D2_START, IMG_FORTRESS_D2_END);
			fortress_animation_display_effect (IMG_FORTRESS_D3_START, IMG_FORTRESS_D3_END);
			fortress_frame_with_words_display_steel_effect (IMG_FORTRESS_D3_END, DMD_MIDDLE_X - 10, DMD_BIG_CY_Bot, "JACKPOT");
			break;
		case 1:
			fortress_animation_display_effect (IMG_FORTRESS_D1_START, IMG_FORTRESS_D1_END);
			fortress_animation_display_effect (IMG_FORTRESS_D2_START, IMG_FORTRESS_D2_END);
			fortress_frame_with_words_display_steel_effect (IMG_FORTRESS_D2_END, DMD_MIDDLE_X - 10, DMD_BIG_CY_Bot, "JACKPOT");
			break;
		case 2:
			fortress_animation_display_effect (IMG_FORTRESS_D3_START, IMG_FORTRESS_D3_END);
			fortress_animation_display_effect (IMG_FORTRESS_D1_START, IMG_FORTRESS_D1_END);
			fortress_frame_with_words_display_steel_effect (IMG_FORTRESS_D4_END, DMD_MIDDLE_X - 10, DMD_BIG_CY_Bot, "JACKPOT");
			break;
		default:
		case 3: //4
			fortress_animation_display_effect (IMG_JACKPOT_START, IMG_JACKPOT_END);
			for (fno = IMG_JACKPOT_END; fno >= IMG_JACKPOT_START; fno -= 2) {
				dmd_alloc_pair ();
				frame_draw(fno);
				dmd_show2 ();
				task_sleep (TIME_100MS);
			}
			break;
		}//end of switch
	deff_exit ();
}//end of mode_effect_deff




void fortress_super_jackpot_deff (void) {
	switch (random_scaled(3)) {
		case 0: sound_start (ST_SPEECH, SPCH_AHHHGGG, SL_2S, PRI_GAME_QUICK3); break;
		case 1: sound_start (ST_SPEECH, SPCH_HURRY_UP, SL_2S, PRI_GAME_QUICK3); break;
		case 2: sound_start (ST_SPEECH, SPCH_CLOSE_ENOUGH, SL_2S, PRI_GAME_QUICK3); break;
	}//END OF SWITCH

	speech_start (SPCH_SUPER_JACKPOT, SL_1S);
	dmd_alloc_low_clean ();
	U16 fno;
	for (fno = IMG_SUPER_JACKPOT_START; fno <= IMG_SUPER_JACKPOT_END; fno += 2) {
		dmd_alloc_pair ();
		frame_draw(fno);
		dmd_show2 ();
		task_sleep (TIME_100MS);
	}
	for (fno = IMG_SUPER_JACKPOT_END; fno >= IMG_SUPER_JACKPOT_START; fno -= 2) {
		dmd_alloc_pair ();
		frame_draw(fno);
		dmd_show2 ();
		task_sleep (TIME_100MS);
	}
	deff_exit ();
}//end of function








void fortress_effect_deff (void) {
	for (;;) {
			dmd_clean_page_low ();
//right side status display
			ll_score_draw_ball ();

//left side display
			sprintf_score(current_score);
			font_render_string_center (&font_var5, 50, 13, sprintf_buffer);
			font_render_string_right (&font_halobold12, 100, 1, "FORTRESS");

			if (fortress_ballsave) {
				sprintf ("%d BALL SAVE", fortress_ballsave);
				font_render_string_center (&font_var5, 50, DMD_MED_CY_BOTTOM_LINE + 3, sprintf_buffer);
			}
			else
			if (fortress_display_counter % 4 != 0) { //draw for 9/10 and blank for 1/10
				if (FORT_TOGGLE == 0) 		{ sprintf ("10 MILLION"); font_render_string_right (&font_fixed6, 85, 21, sprintf_buffer); }
				else if (FORT_TOGGLE == 1)	{ sprintf ("JACKPOT LIT"); font_render_string_right (&font_fixed6, 92, 21, sprintf_buffer); }
				else if (FORT_TOGGLE == 2)	{
					sprintf ("%d JACKPOTS MADE", fortress_jackpot_shots_made);
					font_render_string_right (&font_var5, 85, 19, sprintf_buffer);

					if (get_is_super_jackpot_lit()) sprintf ("SUPER JACKPOT LIT");
					else sprintf ("SHOOT %d ENABLE SUPER", 5 - (fortress_jackpot_shots_made % 5) );
					font_render_string_right (&font_var5, 95, 26, sprintf_buffer);
				}
			} else 						  sprintf ("");
			dmd_show_low();
			task_sleep (TIME_1S);

		if (++fortress_display_counter >= 30) fortress_display_counter  = 0;
		if (fortress_display_counter % 20 == 0) {
			if (++FORT_TOGGLE > 2) FORT_TOGGLE = 0; //change FORT_TOGGLE once per
			if (DM_IN_DMD_TEST) 	score (FORTRESS_MB_SCORE);
		}
	}//END OF ENDLESS LOOP
}//end of function

