/*
 * demolition man
 * museum.c
 * 
 * written by James Cardona
 *
 * handles the lock freezes and the trigger of multiballs
 *
 *
 * */
/* CALLSET_SECTION (museum, __machine5__) */


#include <freewpc.h>
#include "dm/global_constants.h"
#include <diverter.h> //autogenerated by divhold.ct
#include "museum.h"
#include "shaker.h"
#include "ballsave.h"
#include "search.h"
#include <coin.h>



//local variables
score_t		museum_score;
U8			museum_jackpot_shots_made;
U8 			museum_MessageCounter;
U8 museum_display_counter;
U8 MUS_TOGGLE;
U8	museum_ballsave;
__boolean	is_museum_running;


//external variables

//internally called function prototypes  --external found at protos.h



/****************************************************************************
 * multiball definition structure
 ***************************************************************************/
struct mb_mode_ops museum_mode = {
	DEFAULT_MBMODE,
	//.update = , /* The update callback is invoked whenever the state of the multiball changes. */
	.music = MUS_MB,
	.deff_starting = DEFF_MUSEUM_START_EFFECT,
	.deff_running = DEFF_MUSEUM_EFFECT,
	//.deff_ending = ,
//.active_task = 				//	default => .active_task = mb_mode_active_task,
	.prio = PRI_MULTIBALL,		//default => .prio = PRI_NULL,
//.grace_period = 				//default => .grace_period = 500ms
};
//task_gid_t gid_running;
//task_gid_t gid_in_grace;


/****************************************************************************
 * initialize  and exit
 ***************************************************************************/
CALLSET_ENTRY (museum, start_ball) {
	is_museum_running = FALSE;
	museum_ballsave = 0;
}

CALLSET_ENTRY (museum, start_player) {
	score_zero(museum_score);
	museum_jackpot_shots_made = 0; //these need to be zeroed in before we enter the mode so bonus doesn't fake trigger
	museum_MessageCounter = 0;
	is_museum_running = FALSE;
	museum_ballsave = 0;
}//end of function



/****************************************************************************
 * external event listeners
 ****************************************************************************/
CALLSET_ENTRY (museum, music_refresh)  {
	if (in_game && is_museum_running)	music_request (MUS_MB_B, PRI_GAME_QUICK7);
}//end of function



CALLSET_ENTRY (museum, display_update) {
	if (in_game && is_museum_running ) deff_start_bg (DEFF_MUSEUM_EFFECT, PRI_MULTIBALL);
}//end of function



CALLSET_ENTRY (museum, end_ball, tilt) {
	if (is_museum_running) {
		//kill the 5 sec trough recount
		callset_invoke (mb_trough_recount_timer_exit);

		mb_mode_end_ball (&museum_mode);
		jackpot_reset();
		end_super_jackpot_reminder();
	}
	is_museum_running = FALSE;
	museum_ballsave = 0;
}//end of function



//puts in grace period if set
CALLSET_ENTRY (museum, single_ball_play) {
	callset_invoke (mb_trough_recount_timer_exit);

	if (is_museum_running) {
		mb_mode_end_ball (&museum_mode);
		end_super_jackpot_reminder();
//		combo_init();
		//this acts as kind of a grace period for the jackpots
		is_museum_running = FALSE;
		museum_ballsave = 0;
		jackpot_reset();
		diverter_check();
		computer_award_light_recheck();
	}
}//end of function






/****************************************************************************
 *
 * body
 *
 ***************************************************************************/
__boolean get_museum_running (void) {
		if (is_museum_running) return TRUE;
		else return FALSE;
}//end of function







void museum_ballsave_task (void) {
#ifdef CONFIG_DIFFICULTY_LEVEL
	U8 i;
	museum_ballsave = system_config.mb_ballsave;
	for (i = system_config.mb_ballsave; i > 0; i--) {
		task_sleep_sec(1);
		museum_ballsave -= 1;
	}
#elif
	U8 i;
	for (i = 5; i > 0; i--) {
		task_sleep_sec(1);
		museum_ballsave -= 1;
	}
#endif
	museum_ballsave = 0;
	task_exit();
}//end of function







void museum_start(U8 num) {
//	kill_combos();
	computer_light_temp_off();
	is_museum_running = TRUE;
	museum_ballsave = system_config.mb_ballsave;
	mb_mode_start(&museum_mode);

	score_add (museum_score, score_table[MUSEUM_MB_SCORE]);
	score (MUSEUM_MB_SCORE);

	museum_display_counter = 0;
	MUS_TOGGLE = 0;
	multiball_started();//reset all MB start criteria for next time
	deff_start (DEFF_MUSEUM_START_EFFECT);
	diverter_stop();//defined in divhold2.ct

	//LIGHTS
	leff_start (LEFF_MB_START);
			lamp_tristate_flash(LM_MUSEUM_MULTIBALL);
			task_sleep (TIME_2S);
			lamp_tristate_on (LM_MUSEUM_MULTIBALL);
			lamp_tristate_off (LM_FREEZE_1);
			lamp_tristate_off (LM_FREEZE_2);
			lamp_tristate_off (LM_FREEZE_3);
			lamp_tristate_off (LM_FREEZE_4);

	//SOUNDS
			U8 	museum_SoundCounter;
			museum_SoundCounter = random_scaled(2);//from kernal/random.c - pick number from 0 to 2
			if (museum_SoundCounter == 0)
				sound_start (ST_SPEECH, SPCH_WHAT_YOU_DOING_HERE, SL_4S, PRI_GAME_QUICK3);
			else
				sound_start (ST_SPEECH, SPCH_GET_THIS_PARTNER, SL_4S, PRI_GAME_QUICK3);
	task_sleep (TIME_3S);

	//serve balls
	if (num + live_balls >= 5) set_ball_count (5);
	else set_ball_count (num + live_balls);

	task_create_gid1 (GID_MUSEUM_BALL_SAVE, museum_ballsave_task);

	set_all_jackpots(); //all 6 lit

	//just in case - make sure this is running
	ball_search_monitor_start ();

	//recount the trough every 5 secs - this is to handle situations
	//where too many drains in rapid succession cause the game to lose
	//count of live balls - this only happens during MB
	callset_invoke (mb_trough_recount_timer_start);
	set_dm_mode2(MUSEUM_COMPLETED); //for BONUS
}//end of function







//jackpot shot
void museum_jackpot_made(void) {
	score_add (museum_score, score_table[MUSEUM_JP_MB_SCORE]);
	score (MUSEUM_JP_MB_SCORE);
	museum_jackpot_shots_made++;

	if (system_config.disable_shaker == NO) {
		if (system_config.extra_shaker == YES) 	shaker_start (SHAKER_HALF_ON, 2);
		else									shaker_start (SHAKER_ONE_QUARTER_ON, 2);
	}//end of shaker call

	switch (museum_jackpot_shots_made % 5) {
		case 1:	leff_start (LEFF_JACKPOT1); break;
		case 2:	leff_start (LEFF_JACKPOT2); break;
		case 3:	leff_start (LEFF_JACKPOT3); break;
		case 4:	leff_start (LEFF_JACKPOT4); break;
		default:
		case 0:	leff_start (LEFF_JACKPOT); break;
	}
	deff_start (DEFF_MUSEUM_JACKPOT_EFFECT);

	if 		(museum_jackpot_shots_made < 3)	choose_multiple_random_jackpot (3);
	else 									choose_multiple_random_jackpot (2);

	if (DM_IN_CAB_TEST) {	start_super_jackpot_reminder(); }
	else if (museum_jackpot_shots_made % 5 == 0) 	start_super_jackpot_reminder();
}//end of function







void museum_award_super_jackpot(void) {
	score_add (museum_score, score_table[MUSEUM_SUPER_JP_MB_SCORE]);
	score (MUSEUM_SUPER_JP_MB_SCORE);

	if (system_config.disable_shaker == NO) {
		if (system_config.extra_shaker == YES) 	shaker_start (SHAKER_HALF_ON, 2);
		else									shaker_start (SHAKER_ONE_QUARTER_ON, 2);
	}//end of shaker call

	leff_start (LEFF_SUPER_JACKPOT);
	deff_start (DEFF_MUSEUM_SUPER_JACKPOT);
}//end of function




/****************************************************************************
 *
 * display effects
 *
 ****************************************************************************/
void museum_super_jackpot_deff (void) {
	sound_start (ST_SPEECH, SPCH_YOU_GOT_IT, SL_4S, PRI_GAME_QUICK3);
		U16 fno;
		for (fno = IMG_SUPER_JACKPOT_START; fno <= IMG_SUPER_JACKPOT_END; fno += 2) {
			dmd_alloc_pair ();
			frame_draw(fno);
			dmd_show2 ();
			task_sleep (TIME_100MS);
		}
		for (fno = IMG_SUPER_JACKPOT_END; fno >= IMG_SUPER_JACKPOT_START; fno -= 2) {
			dmd_alloc_pair ();
			frame_draw(fno);
			dmd_show2 ();
			task_sleep (TIME_100MS);
		}
	speech_start (SPCH_SUPER_JACKPOT, SL_1S);
	task_sleep_sec (1);
	deff_exit ();
}//end of function




void museum_animation_display_effect (U16 start_frame, U16 end_frame){
	U16 fno;
	for (fno = start_frame; fno <= end_frame; fno += 2) {
		dmd_alloc_pair ();
		frame_draw(fno);
		dmd_show2 ();
		task_sleep (TIME_100MS);
	}//end of inner loop
}



void museum_frame_bitfade_fast (U16 frame){
	dmd_sched_transition (&trans_bitfade_fast);
	dmd_alloc_pair ();
	frame_draw(frame);
	dmd_show2 ();
	task_sleep (TIME_100MS);
}



void museum_frame_with_words_display_steel_effect (U16 frame, U8 x, U8 y, char *words){
	dmd_alloc_pair_clean ();// Clean both pages
	dmd_map_overlay ();
	dmd_clean_page_low ();
		font_render_string_center (&font_halobold12, DMD_MIDDLE_X, DMD_BIG_CY_Top,  "MUSEUM");
		font_render_string_center (&font_halobold12, x, y, words);
	dmd_text_outline ();
	dmd_alloc_pair ();
	frame_draw(frame);
	dmd_overlay_outline ();
	dmd_show2 ();
	task_sleep (TIME_500MS);
}



void museum_start_effect_deff(void) {
	museum_animation_display_effect (IMG_SIMON_FIRE2_START, IMG_SIMON_FIRE2_END);
	museum_frame_with_words_display_steel_effect (IMG_SIMON_FIRE2_END, DMD_MIDDLE_X, DMD_BIG_CY_Bot, "MULTIBALL");
	task_sleep_sec (1);
	deff_exit ();
}//end of mode_effect_deff





void museum_jackpot_sounds_task(void) {
	U8 			jackpot_sounds_MessageCounter;
	if (system_config.swear_sounds == YES || system_config.extra_sounds == YES)
		jackpot_sounds_MessageCounter = random_scaled(5);
	else
		jackpot_sounds_MessageCounter = random_scaled(3);

	if (++museum_jackpot_shots_made % 2 == 0) {
			switch (jackpot_sounds_MessageCounter) {
				case 0: 	sound_start (ST_SPEECH, SPCH_DOUBLE_JACKPOT_WES, SL_4S, PRI_GAME_QUICK3); break;
				case 1: 	sound_start (ST_SPEECH, SPCH_DOUBLE_JACKPOT_SLY, SL_4S, PRI_GAME_QUICK3); break;
				case 2: 	sound_start (ST_SPEECH, SPCH_DOUBLE, SL_4S, PRI_GAME_QUICK3); break;

				case 3: 	sound_start (ST_SPEECH, SPCH_FEEL_LIKE_N_PINBALL_MCHN_SLY, SL_4S, PRI_GAME_QUICK3); break;
				case 4: 	sound_start (ST_SPEECH, SPCH_I_FEEL_LIKE_IM_IN_A_PINBALL_GAME_SIMON, SL_4S, PRI_GAME_QUICK3); break;
}//end of switch
	}//end of if
	else {
		switch (jackpot_sounds_MessageCounter) {
			case 0: 	sound_start (ST_SPEECH, SPCH_AHHHGGG, SL_4S, PRI_GAME_QUICK3); break;
			case 1: 	sound_start (ST_SPEECH, SPCH_JOHN_SCREAM, SL_4S, PRI_GAME_QUICK3); break;
			case 2: 	sound_start (ST_SPEECH, SPCH_UHHN, SL_4S, PRI_GAME_QUICK3); break;

			case 3: 	sound_start (ST_SPEECH, SPCH_JEFF_DAHMER_ILOVE_THIS_GUY_SIMON, SL_4S, PRI_GAME_QUICK3); break;
			case 4: 	sound_start (ST_SPEECH, SPCH_HEY_SWEETHEART_SLY, SL_4S, PRI_GAME_QUICK3); break;
}//end of switch
	}//end of else
	task_sleep (TIME_500MS + TIME_300MS);
	sound_start (ST_EFFECT, SPARKS, SL_1S, PRI_GAME_QUICK3);
	task_sleep (TIME_200MS);
	sound_start (ST_EFFECT, SPARKS, SL_1S, PRI_GAME_QUICK3);
	task_sleep (TIME_200MS);
	sound_start (ST_EFFECT, SPARKS, SL_1S, PRI_GAME_QUICK3);
	task_sleep (TIME_200MS);
	sound_start (ST_EFFECT, ZAPP, SL_2S, PRI_GAME_QUICK3);
	task_sleep (TIME_200MS);
	sound_start (ST_EFFECT, ZAPP, SL_2S, PRI_GAME_QUICK3);
	task_sleep (TIME_200MS);
	sound_start (ST_EFFECT, ZAPP, SL_2S, PRI_GAME_QUICK3);
	task_sleep (TIME_500MS);
	task_exit();
}//end of mode_effect_deff





void museum_jackpot_effect_deff(void) {
	U16 fno;
	if (DM_IN_DMD_TEST) { if (++museum_MessageCounter > 4) museum_MessageCounter = 0; }
	else museum_MessageCounter = random_scaled(5);

	dmd_clean_page_high ();//
	dmd_clean_page_low ();//

	task_create_gid1 (GID_MUSEUM_JACKPOT_SOUND, museum_jackpot_sounds_task);

	switch (museum_MessageCounter) {
		case 0:
			museum_animation_display_effect (IMG_MUSEUM_C2_START, IMG_MUSEUM_C2_END);
			museum_frame_with_words_display_steel_effect (IMG_MUSEUM_C2_END, DMD_MIDDLE_X, DMD_BIG_CY_Bot, "JACKPOT");
			break;
		case 1:
			museum_animation_display_effect (IMG_FIGHT_A_START, IMG_FIGHT_A_END);
			museum_frame_with_words_display_steel_effect (IMG_FIGHT_A_END, DMD_MIDDLE_X, DMD_BIG_CY_Bot, "JACKPOT");
			break;
		case 2:
			museum_animation_display_effect (IMG_MUSEUM_D1_START, IMG_MUSEUM_D1_END);
			museum_animation_display_effect (IMG_MUSEUM_D2_START, IMG_MUSEUM_D2_END);
			museum_frame_with_words_display_steel_effect (IMG_MUSEUM_D2_END, DMD_MIDDLE_X, DMD_BIG_CY_Bot, "JACKPOT");
			break;
		default:
		case 3: //4
			museum_animation_display_effect (IMG_JACKPOT_START, IMG_JACKPOT_END);
			for (fno = IMG_JACKPOT_END; fno >= IMG_JACKPOT_START; fno -= 2) {
				dmd_alloc_pair ();
				frame_draw(fno);
				dmd_show2 ();
				task_sleep (TIME_100MS);
			}
			break;
		}//end of switch
	deff_exit ();
}//end of mode_effect_deff







void museum_effect_deff (void) {
	for (;;) {
		dmd_clean_page_low ();
//right side status display
		ll_score_draw_ball ();


//left side display
		sprintf_score(current_score);
		font_render_string_center (&font_var5, 50, 13, sprintf_buffer);
		font_render_string_right (&font_halobold12, 95, 1, "MUSEUM");
		if (museum_ballsave) {
			sprintf ("%d BALL SAVE", museum_ballsave);
			font_render_string_center (&font_var5, 50, DMD_MED_CY_BOTTOM_LINE + 3, sprintf_buffer);
		}
		else
		if (MUS_TOGGLE == 0) 		{ sprintf ("15 MILLION"); font_render_string_right (&font_fixed6, 85, 21, sprintf_buffer); }
		else if (MUS_TOGGLE == 1)	{ sprintf ("JACKPOT LIT"); font_render_string_right (&font_fixed6, 92, 21, sprintf_buffer); }
		else if (MUS_TOGGLE == 2)	{
			sprintf ("%d JACKPOTS MADE", museum_jackpot_shots_made);
			font_render_string_right (&font_var5, 85, 19, sprintf_buffer);

			if (get_is_super_jackpot_lit()) sprintf ("SUPER LIT");
			else sprintf ("SHOOT %d ENABLE SUPER", 5 - (museum_jackpot_shots_made % 5) );
			font_render_string_right (&font_var5, 95, 26, sprintf_buffer);
		}
		dmd_show_low ();
		task_sleep (TIME_1S);
		if (++museum_display_counter % 3 == 0) { if (++MUS_TOGGLE > 2) MUS_TOGGLE = 0; } //change MUS_TOGGLE
	}//END OF ENDLESS LOOP
	deff_exit();
}//end of function

