/*
 * demolition man
 * wasteland.c
 * 
 * written by James Cardona
 *
 * handles the lock freezes and the trigger of multiballs
 *
 *
 * */
/* CALLSET_SECTION (wasteland, __machine3__) */


#include <freewpc.h>
#include "dm/global_constants.h"
#include <diverter.h> //autogenerated by divhold.ct
#include "wasteland.h"
#include "shaker.h"
#include "ballsave.h"
#include "search.h"
#include <coin.h>



//local variables
score_t		wasteland_score;
U8			wasteland_jackpot_shots_made;
U8			wasteland_MessageCounter;
__boolean	wasteland_start_music;
U8 wasteland_display_counter;
U8 WL_TOGGLE;
__boolean	wasteland_ballsave;
__boolean	is_wasteland_running;


//external variables


//internally called function prototypes  --external found at protos.h



/****************************************************************************
 * multiball definition structure
 ***************************************************************************/
struct mb_mode_ops wasteland_mode = {
	DEFAULT_MBMODE,
	//.update = , /* The update callback is invoked whenever the state of the multiball changes. */
	.music = MUS_MB,
	.deff_starting = DEFF_WASTELAND_START_EFFECT,
	.deff_running = DEFF_WASTELAND_EFFECT,
	//.deff_ending = ,
//.active_task = 				//	default => .active_task = mb_mode_active_task,
	.prio = PRI_MULTIBALL,		//default => .prio = PRI_NULL,
//.grace_period = 				//default => .grace_period = 500ms
};
//task_gid_t gid_running;
//task_gid_t gid_in_grace;



/****************************************************************************
 * initialize  and exit
 ***************************************************************************/
CALLSET_ENTRY (wasteland, start_ball) {
	is_wasteland_running = FALSE;
	wasteland_ballsave = FALSE;
}


CALLSET_ENTRY (wasteland, start_player) {
	score_zero(wasteland_score);
	wasteland_jackpot_shots_made = 0; //these need to be zeroed in before we enter the mode so bonus doesn't fake trigger
	wasteland_start_music = FALSE;
	is_wasteland_running = FALSE;
	wasteland_ballsave = FALSE;
}



/****************************************************************************
 * external event listeners
 ****************************************************************************/
CALLSET_ENTRY (wasteland, music_refresh)  {
//	if (wasteland_start_music)				music_request (GROUND_HUMM, PRI_GAME_QUICK8);
//	else 									mb_mode_music_refresh (&wasteland_mode);
	if (in_game && is_wasteland_running )	music_request (MUS_MB_A, PRI_GAME_QUICK7);
}//end of function



CALLSET_ENTRY (wasteland, display_update) {
	if (is_wasteland_running )
			deff_start_bg (DEFF_WASTELAND_EFFECT, PRI_MULTIBALL);
}//end of function



CALLSET_ENTRY (wasteland, end_ball, tilt) {
	if (is_wasteland_running ) {
		//kill the 5 sec trough recount
		callset_invoke (mb_trough_recount_timer_exit);

		mb_mode_end_ball (&wasteland_mode);
		jackpot_reset();
		end_super_jackpot_reminder();
	}
	is_wasteland_running = FALSE;
	wasteland_ballsave = FALSE;
}//end of function



//puts in grace period if set
CALLSET_ENTRY (wasteland, single_ball_play) {
	if (is_wasteland_running) {
		mb_mode_end_ball (&wasteland_mode);
		callset_invoke (mb_trough_recount_timer_exit);
		end_super_jackpot_reminder();
	//	combo_init();

		//this acts as kind of a grace period for the jackpots
		task_sleep_sec(3);
		is_wasteland_running = FALSE;
		jackpot_reset();
		diverter_check();
		computer_award_light_recheck();
	}
}//end of function


/*
//if a ball drains during the mode and with time still on the ballsave timer - send it back in play
ALLSET_BOOL_ENTRY (wasteland, ball_drain) { //thrown by device.c
	if	(is_wasteland_running && wasteland_ballsave)	{
		sound_start (ST_SPEECH, SPCH_AHHHGGG, SL_2S, PRI_GAME_QUICK2);
		serve_ball_auto ();
		return FALSE; //this is not a valid drain, don't count it
	}
	else return TRUE; //this is a valid drain
}//end of callset
*/







/****************************************************************************
 *
 * body
 *
 ***************************************************************************/
__boolean get_wasteland_running (void) {
		if (is_wasteland_running) return TRUE;
		else return FALSE;
}//end of function



void wasteland_ballsave_task (void) {
#ifdef CONFIG_DIFFICULTY_LEVEL
	task_sleep_sec(system_config.mb_ballsave);
#elif
	task_sleep_sec(5);
#endif
	wasteland_ballsave = FALSE;
	task_exit();
}//end of function




void wasteland_start_sounds (void) {
	U8 i;
	for(i = 0; i < 6; i++) {
		sound_start (ST_ANY, SIREN, SL_1S, PRI_GAME_QUICK2);
		task_sleep (TIME_500MS);
	}
	task_exit();
}//end of function





void wasteland_start(U8 num) {
//	kill_combos();
	computer_light_temp_off();
	task_create_gid1 (GID_WASTELAND_START_NOISE, wasteland_start_sounds);
	is_wasteland_running = TRUE;
	mb_mode_start(&wasteland_mode);

	score_add (wasteland_score, score_table[WASTELAND_MB_SCORE]);
	score (WASTELAND_MB_SCORE);

	wasteland_display_counter = 0;
	WL_TOGGLE = 0;
	wasteland_ballsave = TRUE;

	multiball_started();//reset all MB start criteria for next time
	deff_start (DEFF_WASTELAND_START_EFFECT);
	diverter_stop();//defined in divhold2.ct

	//LIGHTS
	leff_start (LEFF_MB_START);
			lamp_tristate_flash(LM_WASTELAND_MULTIBALL);
			task_sleep (TIME_2S);
			lamp_tristate_on (LM_WASTELAND_MULTIBALL);
			lamp_tristate_off (LM_FREEZE_1);
			lamp_tristate_off (LM_FREEZE_2);
			lamp_tristate_off (LM_FREEZE_3);
			lamp_tristate_off (LM_FREEZE_4);

	//SOUNDS
			U8 	wasteland_SoundCounter;
			wasteland_SoundCounter = random_scaled(2);//from kernal/random.c - pick number from 0 to 2
			if (wasteland_SoundCounter == 0)
				sound_start (ST_SPEECH, SPCH_IN_THIS_CENTURY, SL_4S, PRI_GAME_QUICK2);
			else
				sound_start (ST_SPEECH, SPCH_FEEL_GOOD_TOO, SL_4S, PRI_GAME_QUICK2);
	task_sleep (TIME_3S);
	wasteland_start_music = FALSE; //for to kill the music

	//serve balls
	if (num + live_balls >= 5) set_ball_count (5);
	else set_ball_count (num + live_balls);
	task_create_gid1 (GID_WASTELAND_BALL_SAVE, wasteland_ballsave_task);

	//task_sleep (TIME_3S);

	set_all_jackpots(); //all 6 lit
	//recount the trough every 5 secs - this is to handle situations
	//where too many drains in rapid succession cause the game to lose
	//count of live balls - this only happens during MB
	callset_invoke (mb_trough_recount_timer_start);

	//just in case - make sure this is running
	ball_search_monitor_start ();
	set_dm_mode2(WASTELAND_COMPLETED); //for BONUS
}//end of function





//jackpot shot
void wasteland_jackpot_made(void) {
	score_add (wasteland_score, score_table[WASTELAND_JP_MB_SCORE]);
	score (WASTELAND_JP_MB_SCORE);
	wasteland_jackpot_shots_made++;

	if (system_config.disable_shaker == NO) {
		if (system_config.extra_shaker == YES) 	shaker_start (SHAKER_HALF_ON, 2);
		else									shaker_start (SHAKER_ONE_QUARTER_ON, 2);
	}//end of shaker call

	switch (wasteland_jackpot_shots_made % 5) {
		case 1:	leff_start (LEFF_JACKPOT1); break;
		case 2:	leff_start (LEFF_JACKPOT2); break;
		case 3:	leff_start (LEFF_JACKPOT3); break;
		case 4:	leff_start (LEFF_JACKPOT4); break;
		default: leff_start (LEFF_JACKPOT); break;
	}
	deff_start (DEFF_WASTELAND_JACKPOT_EFFECT);

	choose_multiple_random_jackpot(3);

	if (DM_IN_CAB_TEST) {	start_super_jackpot_reminder(); }
	else			if (wasteland_jackpot_shots_made % 5 == 0) 	start_super_jackpot_reminder();
}//end of function





void wasteland_award_super_jackpot(void) {
	score_add (wasteland_score, score_table[WASTELAND_SUPER_JP_MB_SCORE]);
	score (WASTELAND_SUPER_JP_MB_SCORE);

	if (system_config.disable_shaker == NO) {
		if (system_config.extra_shaker == YES) 	shaker_start (SHAKER_HALF_ON, 2);
		else									shaker_start (SHAKER_ONE_QUARTER_ON, 2);
	}//end of shaker call

	leff_start (LEFF_SUPER_JACKPOT);
	deff_start(DEFF_WASTELAND_SUPER_JACKPOT);
}//end of function





/****************************************************************************
 *
 * display effects
 *
 ****************************************************************************/
void wasteland_super_jackpot_deff (void) {
	sound_start (ST_SPEECH, SPCH_AHHHGGG, SL_2S, PRI_GAME_QUICK2);
	U16 fno;
	for (fno = IMG_SUPER_JACKPOT_START; fno <= IMG_SUPER_JACKPOT_END; fno += 2) {
		dmd_alloc_pair ();
		frame_draw(fno);
		dmd_show2 ();
		task_sleep (TIME_100MS);
	}
	for (fno = IMG_SUPER_JACKPOT_END; fno >= IMG_SUPER_JACKPOT_START; fno -= 2) {
		dmd_alloc_pair ();
		frame_draw(fno);
		dmd_show2 ();
		task_sleep (TIME_100MS);
	}
	speech_start (SPCH_SUPER_JACKPOT, SL_1S);
	task_sleep_sec (1);
	deff_exit ();
}//end of function




void wasteland_animation_display_effect (U16 start_frame, U16 end_frame){
	U16 fno;
	for (fno = start_frame; fno <= end_frame; fno += 2) {
		dmd_alloc_pair ();
		frame_draw(fno);
		dmd_show2 ();
		task_sleep (TIME_100MS);
	}//end of inner loop
}//end of function




void wasteland_frame_with_words_display_steel_effect (U16 frame, U8 x, U8 y, char *words){
	dmd_alloc_pair_clean ();// Clean both pages
	dmd_map_overlay ();
	dmd_clean_page_low ();
		font_render_string_center (&font_halobold12, DMD_MIDDLE_X, DMD_BIG_CY_Top, "WASTELAND");
		font_render_string_center (&font_halobold12, x, y, words);
	dmd_text_outline ();
	dmd_alloc_pair ();
	frame_draw(frame);
	dmd_overlay_outline ();
	dmd_show2 ();
	task_sleep (TIME_500MS);
}//end of function




void wasteland_frame_bitfade_fast (U16 frame){
	dmd_sched_transition (&trans_bitfade_fast);
	dmd_alloc_pair ();
	frame_draw(frame);
	dmd_show2 ();
	task_sleep (TIME_100MS);
}//end of function





void wasteland_start_effect_deff(void) {
	dmd_alloc_pair_clean ();// Clean both pages
	wasteland_animation_display_effect (IMG_WASTELAND_A1_START, IMG_WASTELAND_A1_END);
	wasteland_frame_bitfade_fast(IMG_WASTELAND_A2_START);
	wasteland_animation_display_effect (IMG_WASTELAND_A2_START, IMG_WASTELAND_A2_END);
	wasteland_frame_bitfade_fast(IMG_WASTELAND_A3_START);
	wasteland_animation_display_effect (IMG_WASTELAND_A3_START, IMG_WASTELAND_A3_END);
	wasteland_frame_with_words_display_steel_effect(IMG_WASTELAND_A3_END, DMD_MIDDLE_X, DMD_BIG_CY_Bot, "MULTIBALL");
	task_sleep_sec (1);
		deff_exit ();
}//end of function




void wasteland_jackpot_sounds_task(void) {
	U8 			wasteland_MessageCounter;

	if (system_config.swear_sounds == YES) {
		//this doubles the chance that a swear would occur
		wasteland_MessageCounter = random_scaled(9);
		if (wasteland_MessageCounter >= 6) wasteland_MessageCounter -= 3;
	}
	else {
		wasteland_MessageCounter = random_scaled(3);
	}

	if (++wasteland_jackpot_shots_made % 2 == 0) {
			switch (wasteland_MessageCounter) {
				case 0: 	sound_start (ST_SPEECH, SPCH_DOUBLE_JACKPOT_WES, SL_4S, PRI_GAME_QUICK2); break;
				case 1: 	sound_start (ST_SPEECH, SPCH_DOUBLE_JACKPOT_SLY, SL_4S, PRI_GAME_QUICK2); break;
				case 2: 	sound_start (ST_SPEECH, SPCH_DOUBLE, SL_4S, PRI_GAME_QUICK2); break;

				case 3: 	sound_start (ST_SPEECH, SPCH_VLGR_AS_DONT_BITE_SIMON, SL_4S, PRI_GAME_QUICK2); break;
				case 4: 	sound_start (ST_SPEECH, SPCH_VLGR_PEOPLES_RIGHT_TO_BE_ASHL_SIMON, SL_4S, PRI_GAME_QUICK2); break;
				case 5: 	sound_start (ST_SPEECH, SPCH_VLGR_KISS_MY_AS3_SLY, SL_4S, PRI_GAME_QUICK2); break;
}//end of switch
	}//end of if
	else {
		switch (wasteland_MessageCounter) {
			case 0: 	sound_start (ST_SPEECH, SPCH_AHHHGGG, SL_4S, PRI_GAME_QUICK2); break;
			case 1: 	sound_start (ST_SPEECH, SPCH_JOHN_SCREAM, SL_4S, PRI_GAME_QUICK2); break;
			case 2: 	sound_start (ST_SPEECH, SPCH_UHHN, SL_4S, PRI_GAME_QUICK2); break;

			case 3: 	sound_start (ST_SPEECH, SPCH_VLGR_AS_DONT_BITE_SIMON, SL_4S, PRI_GAME_QUICK2); break;
			case 4: 	sound_start (ST_SPEECH, SPCH_VLGR_PEOPLES_RIGHT_TO_BE_ASHL_SIMON, SL_4S, PRI_GAME_QUICK2); break;
			case 5: 	sound_start (ST_SPEECH, SPCH_VLGR_KISS_MY_AS3_SLY, SL_4S, PRI_GAME_QUICK2); break;
}//end of switch
	}//end of else
	task_sleep (TIME_500MS);
	sound_start (ST_EFFECT, MACHINE14_SHORT, SL_1S, PRI_GAME_QUICK2);
	task_sleep (TIME_200MS);
	sound_start (ST_EFFECT, MACHINE14_SHORT, SL_1S, PRI_GAME_QUICK2);
	task_sleep (TIME_200MS);
	sound_start (ST_EFFECT, MACHINE14_SHORT, SL_1S, PRI_GAME_QUICK2);
	task_sleep (TIME_200MS);
	sound_start (ST_EFFECT, MACHINE14_SHORT, SL_1S, PRI_GAME_QUICK2);
	task_sleep (TIME_200MS);
	sound_start (ST_EFFECT, MACHINE14_LONG, SL_2S, PRI_GAME_QUICK2);
	task_sleep (TIME_500MS);
	task_exit();
}//end of function





void wasteland_jackpot_effect_deff(void) {
	U16 fno;
		if (DM_IN_DMD_TEST) {	if (++wasteland_MessageCounter > 4) wasteland_MessageCounter = 0; }
		else wasteland_MessageCounter = random_scaled(5);

		dmd_alloc_pair_clean ();
		task_create_gid1 (GID_WASTELAND_JACKPOT_SOUND, wasteland_jackpot_sounds_task);

		switch (wasteland_MessageCounter) {
			case 0:
				wasteland_animation_display_effect (IMG_WASTELAND_A2_START, IMG_WASTELAND_A2_END);
				wasteland_frame_with_words_display_steel_effect (IMG_WASTELAND_A2_END, DMD_MIDDLE_X, DMD_BIG_CY_Bot, "JACKPOT");
				break;
			case 1:
				wasteland_animation_display_effect (IMG_WASTELAND_A3_START, IMG_WASTELAND_A3_END);
				wasteland_frame_with_words_display_steel_effect (IMG_WASTELAND_A3_END, DMD_MIDDLE_X, DMD_BIG_CY_Bot, "JACKPOT");
				break;
			case 2:
				wasteland_animation_display_effect (IMG_WASTELAND_A1_START, IMG_WASTELAND_A1_END);
				wasteland_frame_with_words_display_steel_effect (IMG_WASTELAND_A1_END, DMD_MIDDLE_X, DMD_BIG_CY_Bot, "JACKPOT");
				break;
			default:
			case 3: //4
				wasteland_animation_display_effect (IMG_JACKPOT_START, IMG_JACKPOT_END);
				for (fno = IMG_JACKPOT_END; fno >= IMG_JACKPOT_START; fno -= 2) {
					dmd_alloc_pair ();
					frame_draw(fno);
					dmd_show2 ();
					task_sleep (TIME_100MS);
				}
				break;
			}//end of switch
		deff_exit ();
}//end of mode_effect_deff






void wasteland_effect_deff (void) {
	for (;;) {
		dmd_clean_page_low ();
//right side status display
		ll_score_draw_ball ();

//left side display
		sprintf_score(current_score);
		font_render_string_center (&font_var5, 50, 13, sprintf_buffer);
		font_render_string_right (&font_halobold12, 84, 1, "WASTE");
		if (ballsave_test_active()) {
			sprintf ("%d BALL SAVE", ballsave_get_timer());
			font_render_string_center (&font_var5, 50, DMD_MED_CY_BOTTOM_LINE + 3, sprintf_buffer);
		}
		else {
			if (WL_TOGGLE == 0) 		{ sprintf ("15 MILLION"); font_render_string_right (&font_fixed6, 85, 21, sprintf_buffer); }
			else if (WL_TOGGLE == 1)	{ sprintf ("JACKPOT LIT"); font_render_string_right (&font_fixed6, 92, 21, sprintf_buffer); }
			else if (WL_TOGGLE == 2)	{
				sprintf ("%d JACKPOTS MADE", wasteland_jackpot_shots_made);
				font_render_string_right (&font_var5, 85, 19, sprintf_buffer);

				if (get_is_super_jackpot_lit()) sprintf ("SUPER LIT");
				else sprintf ("SHOOT %d ENABLE SUPER", 5 - (wasteland_jackpot_shots_made % 5) );
				font_render_string_right (&font_var5, 95, 26, sprintf_buffer);
			}
		}
		dmd_show_low ();
		task_sleep (TIME_1S);
		if (++wasteland_display_counter % 5 == 0) { if (++WL_TOGGLE > 2) WL_TOGGLE = 0; } //change WL_TOGGLE once per second
	}//END OF ENDLESS LOOP
}//end of function

