/*
 * demolition man
 * ramps.c
 *
 * written by James Cardona
 *
 * Location Description:
 * There are 4 ramps total
 *
 * Left Ramp: Directly to the right of the left loop is this ramp which always
 * feeds to the left inlane. It can be lit for "Quick Freeze" and the "Car Chase" round.
 * Lights are, from bottom up, Quick Freeze, Car Chase, Explode, Jackpot, Combo arrow.
 *
 * Center Ramp (the ACMag): Located at the very top of the playfield, it is
 * a wide ramp (three pinball widths wide) that is triggered only by a gate.
 * Balls drop immediately and roll either down the left loop or into
 * the MTL rollovers. The center ramp has a Jackpot lamp and a Combo arrow.
 * The Center Ramp is bounded on the left by the Upper Rebound and on the right
 * by the left jet bumper.
 *
 * Side Ramp: This is a small, twisting, and difficult ramp just below the
 * Computer. It is used for the skill shot. The Side Ramp has a jackpot
 * lamp and a Combo Arrow.
 *
 * Right Ramp: This is a tall ramp similar to the right ramp in Judge Dredd.
 * It has a diverter which normally sends the ball to the right inlane,
 * but it can send the ball to the Cryo-Claw when that feature is available.
 * It's also used during the Car Chase round, and to score Super Jackpots.
 * Lights are, from bottom up, Claw Ready, Car Chase, Explode, Jackpot, Combo
 * Arrow. There is a Super Jackpot light mounted over the ramp.
 *
 *
 * Scoring Description: (original game)
 * Ramps score depending on mode running as follows:
 * basic score - no mode running: ramp 100k enter - 250k exit
 * explode running: scores only on left and right ramps- 5 to 15 million depending on time left
 * car crash running: scores only on left and right ramps- 10 million
 * car chase in orig is not a mode but single lights that can be lit on either L or R ramp
 * MB quick freeze - right inlane activates quick freeze light from left ramp - shoot left ramp to freeze.

 * Scoring Description: (my rules)
 * same as original except:
 * car chase is a mode here (not in original) --L or R ramp for xx million shot --handled in carchase.c
 *
 *
 */

#include <freewpc.h>
#include <diverter.h> //autogenerated by divhold.ct
#include "ngg/global_constants.h" 
#include "shaker.h"

//constants
U8		rampSoundsCounter;
U8 		NumRampsSounds; //num between 0 and 24 == 25 total
const sound_code_t rampSoundsArray[] = {	SPCH_NICE_SHOOTING_SLY, 	SPCH_NICE_SHOT_SLY,
											SPCH_GREAT_SHOT_SLY, 		SPCH_GREAT_SHOOTING, 		SPCH_NOW_THATS_WHAT_I_CALL_SHOOTING,
											SPCH_OHH_YEAH1, 			SPCH_OHH_YEAH2, 			SPCH_OUTSTANDING_SLY,
											SPCH_NICE, 					SPCH_VERY_NICE, 			SPCH_NICE_MOVE_SLY,
											SPCH_GOOD_ONE, 				SPCH_GREAT_SHOT, 			SPCH_GOOD_SHOT,
											SPCH_NICE_SHOT, 			SPCH_NICE_SHOOTING, 	SPCH_NICE_SHOOTING,
											SPCH_EXCELLENT,
											//extra sounds set
											SPCH_HEY_LUKE_HERES_THE_FORCE_SLY,
											//swear rom set
											SPCH_GREAT_PLAYER_GIRL,
											SPCH_LOVE_IT_SQUEEZE_LOVE_HANDLES_GIRL,
											SPCH_TIGHTER_GRIP_GIRL,
											SPCH_LOVE_IT_WHEN_DO_THAT_GIRL,
											SPCH_NICE_FINGERS_GIRL,
											SPCH_VLGR_FAST_TOO_1_CREDIT_SIMON,
											SPCH_VLGR_OKAY_ASHL_SIMON,
											SPCH_VLGR_AS_N_GASOLINE_SIMON,
											SPCH_VLGR_PIDLY_AS_SIMON,
											SPCH_VLGR_CMON_PIECE_OF_SHT_SIMON,
											};


const sound_code_t explosionSoundsArray[] = {	EXPLOSION, EXPLOSION1_SHORT, EXPLOSION1_MED, EXPLOSION1_LONG };

#define 	car_chase_TotalNumOfSounds1  7
const sound_code_t car_chase_SoundsArray1[] = {	SPCH_WOOH, 			SPCH_WOW,					SPCH_STEP_ON_IT,
												SPCH_PUNCH_IT, 		SPCH_PUSH_PEDAL_HARD,		SPCH_GO_LEFT,
												SPCH_CATCH_UP};

//local variables
U8	ramp_SoundCounter;

//external variables

//prototypes
void right_ramp_task (void);
void left_ramp_task (void);
void ramps_flasher (char * flasher);
void side_ramp_task (void);
void ramp_sounds (void);
void carchase_ramp_sounds (void);
void missed_ramp_sounds (void);
void left_ramp_made(void);
void right_ramp_made(void);
void side_ramp_made(void);


/****************************************************************************
 * initialize  and exit
 ***************************************************************************/
CALLSET_ENTRY (ramps, start_player) {
	ramp_SoundCounter = 0;
	flag_off(FLAG_IS_LRAMP_QUICKFREEZE_ACTIVATED);
	flag_off(FLAG_IS_R_RAMP_CLAWREADY);
}//end of function



CALLSET_ENTRY (ramps, start_ball) {
	if (	flag_test(FLAG_IS_R_RAMP_CLAWREADY)
		&&	!get_back_in_the_fridge_running()
		&&	!get_back_in_the_fridge_ending()
		&&	!is_carchase_mode_running()
		&&	!is_explode_mode_running()
		&&	!get_fortress_running ()
		&&	!get_museum_running ()
		&&  !get_cryoprison_running ()
		&&  !get_wasteland_running ()
		&&  !get_demotime_running ()
		&&	!get_capture_simon_arrows (CAPSIM_RIGHTRAMP)
		&&	!is_huxley_running ()  )
												rramp_clawready_on ();
	else										rramp_clawready_off ();

	if 	(flag_test(FLAG_IS_LRAMP_QUICKFREEZE_ACTIVATED)) lamp_tristate_on (LM_QUICK_FREEZE); else lamp_tristate_off (LM_QUICK_FREEZE);

	lamp_tristate_off (LM_LEFT_RAMP_JACKPOT);
	lamp_tristate_off (LM_SIDE_RAMP_JACKPOT);
	lamp_tristate_off (LM_CENTER_RAMP_JACKPOT);
	lamp_tristate_off (LM_RIGHT_RAMP_JACKPOT);
	lamp_tristate_off (LM_LEFT_RAMP_EXPLODE);
	lamp_tristate_off (LM_RIGHT_RAMP_EXPLODE);
	lamp_tristate_off (LM_LEFT_RAMP_CAR_CHASE);
	lamp_tristate_off (LM_RIGHT_RAMP_CAR_CHASE);
}//end of function




CALLSET_ENTRY (ramps, end_ball) {
	lamp_tristate_off (LM_QUICK_FREEZE);
	lamp_tristate_off (LM_LEFT_RAMP_JACKPOT);
	lamp_tristate_off (LM_SIDE_RAMP_JACKPOT);
	lamp_tristate_off (LM_CENTER_RAMP_JACKPOT);
	lamp_tristate_off (LM_RIGHT_RAMP_JACKPOT);
	lamp_tristate_off (LM_LEFT_RAMP_EXPLODE);
	lamp_tristate_off (LM_RIGHT_RAMP_EXPLODE);
	lamp_tristate_off (LM_LEFT_RAMP_CAR_CHASE);
	lamp_tristate_off (LM_RIGHT_RAMP_CAR_CHASE);
}//end of function




/****************************************************************************
 * playfield lights and flags -- MULTIPLE RAMPS AT SAME TIME
 ***************************************************************************/
//called from eyeball_explode.c for explode mode start
void activate_explode_inserts_ramps(void) {
	lamp_tristate_on (LM_LEFT_RAMP_EXPLODE);
	lamp_tristate_on (LM_RIGHT_RAMP_EXPLODE);
}//end of function


void deactivate_explode_inserts_ramps(void) {
	lamp_tristate_off (LM_LEFT_RAMP_EXPLODE);
	lamp_tristate_off (LM_RIGHT_RAMP_EXPLODE);
}//end of function


//called from carcrash.c for carcrash mode start
void carchase_mode_on(void) {
	lamp_tristate_on (LM_LEFT_RAMP_CAR_CHASE);
	lamp_tristate_on (LM_RIGHT_RAMP_CAR_CHASE);
}//end of function

void carchase_mode_off(void) {
	lamp_tristate_off (LM_LEFT_RAMP_CAR_CHASE);
	lamp_tristate_off (LM_RIGHT_RAMP_CAR_CHASE);
}//end of function


/****************************************************************************
 * playfield lights and flags - LEFT RAMP
 ***************************************************************************/
// called by right inlane switch --see inlanes.c
// or called by certain number of standups made --see standupfrenzy.c
void activate_left_ramp_quickfreeze(void) {
	flag_on(FLAG_IS_LRAMP_QUICKFREEZE_ACTIVATED);
	lamp_tristate_on (LM_QUICK_FREEZE);
//	leff_start (LEFF_RAMP_QUICKFREEZE);
}//end of function

void deactivate_left_ramp_quickfreeze(void) {
	flag_off(FLAG_IS_LRAMP_QUICKFREEZE_ACTIVATED);
	lamp_tristate_off (LM_QUICK_FREEZE);
//	leff_stop(LEFF_RAMP_QUICKFREEZE);
}//end of function

void lramp_jackpot_light_on(void) {
	lamp_tristate_on (LM_LEFT_RAMP_JACKPOT);
}//end of function

void lramp_jackpot_light_off(void) {
	lamp_tristate_off (LM_LEFT_RAMP_JACKPOT);
}//end of function

void lramp_arrow_light_on(void) {
	flag_on (FLAG_IS_L_RAMP_ARROW_ACTIVATED);
	lamp_tristate_on (LM_LEFT_RAMP_ARROW);
}//end of function

void lramp_arrow_light_off(void) {
	flag_off (FLAG_IS_L_RAMP_ARROW_ACTIVATED);
	lamp_tristate_off (LM_LEFT_RAMP_ARROW);
}//end of function


/****************************************************************************
 * playfield lights and flags - RIGHT RAMP
 ***************************************************************************/
void rramp_jackpot_light_on(void) {
	lamp_tristate_on (LM_RIGHT_RAMP_JACKPOT);
}//end of function

void rramp_jackpot_light_off(void) {
	lamp_tristate_off (LM_RIGHT_RAMP_JACKPOT);
}//end of function

void rramp_arrow_light_on(void) {
	flag_on (FLAG_IS_R_RAMP_ARROW_ACTIVATED);
	lamp_tristate_on (LM_RIGHT_RAMP_ARROW);
}//end of function

void rramp_arrow_light_off(void) {
	flag_off (FLAG_IS_R_RAMP_ARROW_ACTIVATED);
	lamp_tristate_off (LM_RIGHT_RAMP_ARROW);
}//end of function

//called by left inlane --see inlanes.c
void rramp_clawready_on(void) {
	flag_on(FLAG_IS_R_RAMP_CLAWREADY);
	lamp_tristate_on (LM_CLAW_READY);
	flasher_pulse (FLASH_DIVERTER_FLASHER);
//	leff_start(LEFF_RAMP_CLAWREADY);

	if (system_config.disable_claw == NO) diverter_start();//defined in divhold2.ct
}//end of function

//called by claw after ball is passed to it from elevator
void rramp_clawready_off(void) {
	flag_off(FLAG_IS_R_RAMP_CLAWREADY);
	lamp_tristate_off (LM_CLAW_READY);
	flasher_pulse (FLASH_DIVERTER_FLASHER);
	diverter_stop(); //defined in divhold2.ct
//	leff_stop(LEFF_RAMP_CLAWREADY);
}//end of function


/****************************************************************************
 * playfield lights and flags - CENTER RAMP
 ***************************************************************************/
void cramp_jackpot_light_on(void) {
	lamp_tristate_on (LM_CENTER_RAMP_JACKPOT);
}//end of function

void cramp_jackpot_light_off(void) {
	lamp_tristate_off (LM_CENTER_RAMP_JACKPOT);
}//end of function

void cramp_arrow_light_on(void) {
	flag_on (FLAG_IS_C_RAMP_ARROW_ACTIVATED);
	lamp_tristate_on (LM_CENTER_RAMP_ARROW);
}//end of function

void cramp_arrow_light_off(void) {
	flag_off (FLAG_IS_C_RAMP_ARROW_ACTIVATED);
	lamp_tristate_off (LM_CENTER_RAMP_ARROW);
}//end of function

/****************************************************************************
 * playfield lights and flags - SIDE RAMP
 ***************************************************************************/
void sramp_jackpot_light_on(void) {
	lamp_tristate_on (LM_SIDE_RAMP_JACKPOT);
}//end of function

void sramp_jackpot_light_off(void) {
	lamp_tristate_off (LM_SIDE_RAMP_JACKPOT);
}//end of function

void sramp_arrow_light_on(void) {
	flag_on (FLAG_IS_S_RAMP_ARROW_ACTIVATED);
	lamp_tristate_on (LM_SIDE_RAMP_ARROW);
}//end of function

void sramp_arrow_light_off(void) {
	flag_off (FLAG_IS_S_RAMP_ARROW_ACTIVATED);
	lamp_tristate_off (LM_SIDE_RAMP_ARROW);
}//end of function

/****************************************************************************
 *
 * left ramp
 *
 ***************************************************************************/
void left_ramp_task (void) { task_sleep_sec(2); task_exit(); }


CALLSET_ENTRY (ramps, sw_left_ramp_enter) {
	if (in_game && !in_tilt) {
			task_create_gid1 (GID_LEFT_RAMP_ENTERED, left_ramp_task);
			score (RAMPS_ENTER_SCORE);
			if (is_carchase_mode_running()  ) {
				carchase_ramp_sounds();
				if (system_config.disable_shaker == NO) {
					if (system_config.extra_shaker == YES) 	shaker_start (SHAKER_HALF_ON, 2);
					else									shaker_start (SHAKER_ONE_QUARTER_ON, 2);
				}//end of shaker call
			}

			flasher_pulse (FLASH_LEFT_RAMP_UP); //FLASH followed by name of flasher in caps
			flasher_pulse (FLASH_LEFT_RAMP_LOWER);
			task_sleep (TIME_100MS);
			flasher_pulse (FLASH_LEFT_RAMP_UP);
			flasher_pulse (FLASH_LEFT_RAMP_LOWER);
			task_sleep (TIME_100MS);
			flasher_pulse (FLASH_LEFT_RAMP_UP);
			flasher_pulse (FLASH_LEFT_RAMP_LOWER);
	}//end of 	if (in_game && !in_tilt)
}//end of function



CALLSET_ENTRY (ramps, sw_left_ramp_exit) {
	if (in_game && !in_tilt) {
		leff_start(LEFF_LEFT_RAMP);
		if ( task_kill_gid (GID_LEFT_RAMP_ENTERED) ) left_ramp_made();
	}
}//end of function


void left_ramp_made(void) {
	score (RAMPS_MADE_SCORE);
	if 		(get_skill_shot_enabled()  )							award_skill_shot(3);
	if (get_back_in_the_fridge_running()  ) 					back_in_the_fridge_shot_made();
	if (is_huxley_running ()  )								huxley_mode_shot_made();
	if (get_jackpot_arrows(lramp_mask)  ) 						score_jackpot();
	if (get_capture_simon_arrows (CAPSIM_LEFTRAMP) )			capture_simon_made();
	if (is_prison_break_running () )  							prison_break_made();

	if ( flag_test(FLAG_IS_COMBO_LEFTRAMP_ACTIVATED) ) 		combo_hit();
	else if (get_is_combos_killed ()
		&&	 get_is_combos_restartable ()) 							combo_init();

	//regardless of what else is going on, we can do these
	if (flag_test(FLAG_IS_LRAMP_QUICKFREEZE_ACTIVATED) )	 		increment_freeze(); //goto lock_freeze_mbstart.c
	if (is_explode_mode_running() ) 										explode_made(); //goto eyeball_explode.c for scoring
	if (is_carchase_mode_running()  )										car_chase_ramp_made(); //goto carchase.c for scoring

	//if not in a mode then perform normal sounds and display effects
	if (	!is_explode_mode_running()
		&& 	!is_carchase_mode_running()
		&& 	!get_capture_simon_arrows (CAPSIM_LEFTRAMP) )
				ramp_sounds();
}//end of function


/****************************************************************************
 *
 * right ramp
 *
 ***************************************************************************/
void right_ramp_task (void) { task_sleep_sec(2); task_exit(); }


CALLSET_ENTRY (ramps, sw_right_ramp_enter) {
	if (in_game && !in_tilt) {
			task_create_gid1 (GID_RIGHT_RAMP_ENTERED, right_ramp_task);
			score (RAMPS_ENTER_SCORE);
			if (is_carchase_mode_running()  ) {
				carchase_ramp_sounds();
				if (system_config.disable_shaker == NO) {
					if (system_config.extra_shaker == YES) 	shaker_start (SHAKER_HALF_ON, 2);
					else									shaker_start (SHAKER_ONE_QUARTER_ON, 2);
				}//end of shaker call
			}

			flasher_pulse (FLASH_RIGHT_RAMP_UP);
			flasher_pulse (FLASH_RIGHT_RAMP);
			task_sleep (TIME_100MS);
			flasher_pulse (FLASH_RIGHT_RAMP_UP);
			flasher_pulse (FLASH_RIGHT_RAMP);
			task_sleep (TIME_100MS);
			flasher_pulse (FLASH_RIGHT_RAMP_UP);
			flasher_pulse (FLASH_RIGHT_RAMP);
			task_sleep (TIME_100MS);
	}//end of 	if (in_game && !in_tilt)
}//end of function




CALLSET_ENTRY (ramps, sw_right_ramp_exit) {
	if (in_game && !in_tilt) {
		leff_start(LEFF_RIGHT_RAMP);
		if ( task_kill_gid(GID_RIGHT_RAMP_ENTERED) ) right_ramp_made();
	}
}//end of function


void right_ramp_made(void) {
	score (RAMPS_MADE_SCORE);
	if (get_back_in_the_fridge_running() ) 						back_in_the_fridge_shot_made();
	if (get_is_super_jackpot_lit() )						score_super_jackpot();
	if (get_jackpot_arrows(rramp_mask) ) 					score_jackpot();
	if (is_huxley_running ()  )							huxley_mode_shot_made();
	if (is_prison_break_running () ) 						prison_break_made();
	if (get_capture_simon_arrows (CAPSIM_RIGHTRAMP) )		capture_simon_made();

	if (flag_test (FLAG_IS_COMBO_RIGHTRAMP_ACTIVATED) ) 	combo_hit();
	else if (get_is_combos_killed ()
		&&	 get_is_combos_restartable () ) 						combo_init();

	//regardless of what else is going on, we can do these
	if (is_explode_mode_running()  )							 		explode_made(); //goto eyeball_explode.c for scoring
	if (is_carchase_mode_running()  )									car_chase_ramp_made(); //goto carchase.c for scoring

	//if claw is disabled then and claw ready then right ramp
	//acts like a claw hit
	if (	system_config.disable_claw == YES
		&&	flag_test(FLAG_IS_R_RAMP_CLAWREADY ) )			disabled_claw_hit ();



	//if not in a mode then perform normal sounds and display effects
	if (	!is_explode_mode_running()
		&& 	!is_carchase_mode_running()
		&& 	!get_capture_simon_arrows (CAPSIM_RIGHTRAMP) )
				ramp_sounds();
}//end of function


/****************************************************************************
 *
 * center ramp
 * note: center ramp has only 1 switch
 *
 ***************************************************************************/
CALLSET_ENTRY (ramps, sw_center_ramp) {
	if (in_game && !in_tilt) {
			leff_start(LEFF_CENTER_RAMP);
			score (RAMPS_MADE_SCORE);

			if (get_back_in_the_fridge_running()  ) 					back_in_the_fridge_shot_made();
			if (get_jackpot_arrows(cramp_mask)  ) 					score_jackpot();
			if (is_huxley_running ()  )							huxley_mode_shot_made();
			if (is_acmag_running () ) 								acmag_made();
			if (get_capture_simon_arrows (CAPSIM_CENTERRAMP) )		capture_simon_made();
			if (is_prison_break_running () ) 						prison_break_made();
			if (flag_test (FLAG_LASER_SHOT_ENABLED) )				laser_shot_made();

			if ( flag_test(FLAG_IS_COMBO_CENTERRAMP_ACTIVATED) ) 	combo_hit();
			else if (get_is_combos_killed ()
				&&	 get_is_combos_restartable () ) 					combo_init();

			if (!is_prison_break_running () ) 							ramp_sounds();
	}//end of 	if (in_game && !in_tilt)
}//end of function





/****************************************************************************
 *
 * side ramp
 *
 ***************************************************************************/
void side_ramp_task (void) { task_sleep_sec(2); task_exit(); }


CALLSET_ENTRY (ramps, sw_side_ramp_enter) {
	if (in_game && !in_tilt) {
			task_create_gid1 (GID_SIDE_RAMP_ENTERED, side_ramp_task);
			score (RAMPS_ENTER_SCORE);
			if (is_carchase_mode_running()  ) {
				carchase_ramp_sounds();
				if (system_config.disable_shaker == NO) {
					if (system_config.extra_shaker == YES) 	shaker_start (SHAKER_HALF_ON, 2);
					else									shaker_start (SHAKER_ONE_QUARTER_ON, 2);
				}//end of shaker call
			}

			flasher_pulse (FLASH_SIDE_RAMP); //FLASH followed by name of flasher in caps
			task_sleep (TIME_100MS);

			flasher_pulse (FLASH_DIVERTER_FLASHER); //FLASH followed by name of flasher in caps
			flasher_pulse (FLASH_SIDE_RAMP);
			task_sleep (TIME_100MS);
			flasher_pulse (FLASH_DIVERTER_FLASHER); //FLASH followed by name of flasher in caps
			flasher_pulse (FLASH_SIDE_RAMP);
			task_sleep (TIME_100MS);
			flasher_pulse (FLASH_DIVERTER_FLASHER); //FLASH followed by name of flasher in caps
			flasher_pulse (FLASH_SIDE_RAMP);
			task_sleep (TIME_100MS);
	}//end of 	if (in_game && !in_tilt)
}//end of function



CALLSET_ENTRY (ramps, sw_side_ramp_exit) {
	if (in_game && !in_tilt) {
		leff_start(LEFF_SIDE_RAMP);
		if ( task_kill_gid(GID_SIDE_RAMP_ENTERED) ) side_ramp_made();
	}//end of 	if (in_game && !in_tilt)
}//end of function




void side_ramp_made(void) {
	score (RAMPS_MADE_SCORE);

	if 		(get_skill_shot_enabled()  )							award_skill_shot(2);
	if (get_back_in_the_fridge_running()  ) 					back_in_the_fridge_shot_made();
	if (get_jackpot_arrows(sramp_mask)  ) 						score_jackpot();
	if (get_capture_simon_arrows(CAPSIM_SIDERAMP) )			capture_simon_made();
	if (is_huxley_running ()  )								huxley_mode_shot_made();
	if (is_prison_break_running () ) 							prison_break_made();

	if ( flag_test(FLAG_IS_COMBO_SIDERAMP_ACTIVATED) ) 		combo_hit();
	else if (get_is_combos_killed ()
		&&	 get_is_combos_restartable () ) 						combo_init();

	if (is_carchase_mode_running()  )										car_chase_ramp_made(); //goto carchase.c for scoring

	//if not in a mode then perform normal sounds and display effects
	if (	!is_carchase_mode_running()
		&& 	!get_capture_simon_arrows(CAPSIM_SIDERAMP) )
				ramp_sounds();
}//end of function




/****************************************************************************
 *
 * sound effects
 *
 ****************************************************************************/
void ramp_sounds (void) {
	U8 rand_sound;
	if (system_config.swear_sounds == YES) {
		NumRampsSounds = 29;
		//this doubles the chance that a swear would occur
		rand_sound = random_scaled(39);
		if (rand_sound >= 29) rand_sound -= 10;
	}
	else if (system_config.extra_sounds == YES) {
		NumRampsSounds = 19;
		rand_sound = random_scaled(NumRampsSounds);
	}
	else {
		NumRampsSounds = 18;
		rand_sound = random_scaled(NumRampsSounds);
	}

	if (++rampSoundsCounter % 3 == 0)
						sound_start (ST_SPEECH, rampSoundsArray[rand_sound], SL_4S, PRI_GAME_QUICK5);
	else if (rampSoundsCounter % 3 == 1)
						sound_start (ST_ANY,explosionSoundsArray[random_scaled(4)], SL_4S, PRI_GAME_QUICK5);
}//end of function



void carchase_ramp_sounds(void) {
	sound_start (ST_SAMPLE, CAR_SKID, SL_3S, PRI_GAME_QUICK1);
	ramp_SoundCounter = random_scaled(car_chase_TotalNumOfSounds1);//from kernal/random.c
	sound_start (ST_SPEECH, car_chase_SoundsArray1[ramp_SoundCounter], SL_4S, PRI_GAME_QUICK2);
}//end of function


